"""
cli.py
======

Script/CLI equivalent to the GUI. Same ``api.py`` calls that
``zbemt.gui.app`` uses; zero widgets, zero physics, zero direct I/O --
everything goes through ``api.py``.

CLI<->GUI<->.bemt parity: every flag of this script sets a
``Project``/``BEMTConfig`` field that is also editable from the GUI, and
every ``.bemt`` file generated by any of the three paths (GUI, CLI,
manual editing) is read back identically by the other two.

Two equivalent ways to use it (every command-line flag has a
corresponding Python field in ``RunOptions``, and vice versa):

    from zbemt.cli import main, RunOptions
    main(["--project", "projects/MyProject", "--rpm", "300"])
    main(options=RunOptions(project="projects/MyProject", rpm=300.0))

Typical command-line usage (``zbemt`` is the installed entry point;
``python -m zbemt.cli`` works identically):

    zbemt --project projects/MyProject
    zbemt --project projects/MyProject --from-bemt-batch hover_sweep
    zbemt --project projects/MyProject --list-batches
    zbemt --new projects/MyProject --radius 0.6 --rpm 1200 \\
        --inflow pitt_peters_steady --dynamic-stall --save-as projects/MyProject
    zbemt --project projects/MyProject \\
        --gen-neuralfoil --airfoil-geometry naca2412 \\
        --reynolds 1e5,5e5,1e6 --mach 0.1,0.3 --alpha-range -10:20:0.5 \\
        --export-table saida/naca2412_neuralfoil.csv
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
import typing
from pathlib import Path

import numpy as np

# Running the FILE directly (`python zbemt/cli.py`, or the "Run" button of
# an IDE with this file open) executes it as a standalone script, without a
# package -- and then every `from . import ...` below raises
# "attempted relative import with no known parent package". Putting the
# repository root on `sys.path` and declaring `__package__` makes the
# relative import resolve, so the "Run" button works the same as
# `python -m zbemt.cli`. Outside that case (normal import, `-m`), this
# block does not run and nothing changes.
if __name__ == "__main__" and __package__ in (None, ""):    # pragma: no cover
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    __package__ = "zbemt"

from . import api
from .models import FlightCondition, BatchDefinition, RotorGeometryDef, AirfoilDef
from . import geometry
from . import airfoils
from .bemt import BEMTConfig


# Running with no arguments (e.g. the IDE's "Run" button) uses this example
# project by default.
DEFAULT_PROJECT_PATH = "projects/starter_rotor"

#: RPM for the no-argument run. Must be explicit here: RPM is MANDATORY in
#: every flight condition (`studies._require_rpm` has no default, on
#: purpose -- BEMT non-dimensionalizes everything by Omega*R) and
#: `starter_rotor` ships no saved cases, so without this the no-argument
#: run used to end in a validation ERROR ("Flight condition without
#: RPM") instead of a clean run -- a terrible first impression for
#: someone who just hit "Run" to see what the program does.
DEFAULT_RPM = 600.0


# =============================================================================
# Argument parsing
#
# Two ways to set this script's options (requested by the project owner:
# "every command-line flag must also be settable directly in Python"):
#
#   from zbemt.cli import main, RunOptions
#   main(["--project", "projects/X", "--rpm", "300", "--mu_x", "0.2"])
#   main(options=RunOptions(project="projects/X", rpm=300.0, mu_x=0.2))
#
# `RunOptions` is generated from the argparse.ArgumentParser itself (via
# `_build_run_options_dataclass`), so the two forms can never diverge:
# every flag defined in `_build_parser` automatically becomes a
# `RunOptions` field with the same default, and there is no way to add a
# flag without the corresponding Python field (or vice versa).
# =============================================================================

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run a zBEMT project (new or existing) via api.py, "
                     "without GUI — full parity with GUI (docs/parity_registry.md).",
    )
    project_group = p.add_mutually_exclusive_group(required=True)
    project_group.add_argument("--project", metavar="PATH",
                                help="Open an existing project in this folder.")
    project_group.add_argument("--new", metavar="PATH",
                                help="Create a new project (default geometry/airfoil) in this folder.")

    p.add_argument("--name", default=None,
                    help="Project name, used only with --new (default: folder name).")
    p.add_argument("--save-as", metavar="PATH", default=None,
                    help="Save the project (with all fields set by the flags below "
                         "already applied) in this folder before running. Omit = does not persist "
                         "flags to disk (only affects this call's execution).")

    # --- listing/selecting saved batches and cases (Part 3.3, item 1-2) --
    p.add_argument("--list-batches", action="store_true",
                    help="List saved batches in project.batches and exit.")
    p.add_argument("--list-cases", action="store_true",
                    help="List saved cases in project.saved_cases and exit.")
    p.add_argument("--from-bemt-batch", metavar="NAME", default=None,
                    help="Run the saved batch NAME (project.batches) instead of creating "
                         "an ad hoc condition.")
    p.add_argument("--from-bemt-case", metavar="NAME", default=None,
                    help="Run the saved case NAME (project.saved_cases).")

    # --- NeuralFoil: polar table generation (Phase 7, docs/plano_v3.md
    # Part 7.4) -- mode independent of running BEMT, exits right after
    # generating (and optionally exporting/applying). ---------------------
    neuralfoil_group = p.add_argument_group("NeuralFoil (Phase 7 -- polar table generation)")
    neuralfoil_group.add_argument(
        "--gen-neuralfoil", action="store_true",
        help="Generate a polar table via NeuralFoil for --airfoil-geometry and exit "
             "(does not run BEMT). Requires the 'neuralfoil' package (pip install neuralfoil).")
    neuralfoil_group.add_argument(
        "--airfoil-geometry", metavar="SPEC", default=None,
        help="Airfoil geometry: NACA4/5 code (e.g. 'naca2412', 'naca23012') or a "
             f"typical blade/rotor preset ({', '.join(sorted(airfoils.AIRFOIL_PRESETS))}).")
    neuralfoil_group.add_argument(
        "--reynolds", metavar="R1,R2,...", default=None,
        help="List of Reynolds for NeuralFoil sweep, e.g. '1e5,5e5,1e6'.")
    neuralfoil_group.add_argument(
        "--mach", metavar="M1,M2,...", default=None,
        help="List of Mach for NeuralFoil sweep, e.g. '0.1,0.3'.")
    neuralfoil_group.add_argument(
        "--alpha-range", metavar="MIN:MAX:STEP", default="-10:20:0.5",
        help="Alpha [deg] range for NeuralFoil sweep (default: -10:20:0.5).")
    neuralfoil_group.add_argument(
        "--export-table", metavar="PATH", default=None,
        help="Write the generated polar table to PATH (CSV, import format). "
             "If omitted, the table is appended to project.airfoil.table_slices and the project "
             "is saved (equivalent to applying directly from GUI).")

    # --- ad hoc condition (used only if no --from-bemt-* is given and the
    # project has no batch.conditions) ----------------------------------
    # Phase 8 (docs/CHANGELOG.md): mu_x/J_x and Vz/alpha-disk are
    # INTERCHANGEABLE representation pairs of the same physical quantity
    # (Sec.6c of bemt.py) -- --mu_x and --J_x are mutually exclusive (same
    # for --vz and --alpha-rotor-deg), parity with the GUI's unit dropdown
    # (RunCaseTab/RunBatchTab).
    p.add_argument("--rpm", type=float, default=None, help="RPM for ad hoc condition.")
    long_group = p.add_mutually_exclusive_group()
    long_group.add_argument("--mux", dest="mu_x", type=float, default=None,
                             help="Ad hoc advance ratio, rotor convention (default 0.0, hover). "
                                  "Alternative to --J_x.")
    long_group.add_argument("--jx", dest="J_x", type=float, default=None,
                             help="Ad hoc advance ratio, propeller convention (J_x=pi*mu_x). "
                                  "IN-PLANE, like --mu_x: for the axial advance ratio of a "
                                  "propeller use --jx. Alternative to --mu_x.")
    long_group.add_argument("--alpha-disk-deg", dest="alpha_disk_deg", type=float, default=None,
                             help="Angle [deg] between the free stream and the SHAFT "
                                  "(0 = straight axial cruise, the propeller convention). "
                                  "The IN-PLANE component is derived from it and from the "
                                  "axial one (--vz/--jz/--muz), which is therefore required. "
                                  "Complement of --alpha-rotor-deg; the two are mutually "
                                  "exclusive because neither would set the velocity scale.")
    axial_group = p.add_mutually_exclusive_group()
    axial_group.add_argument("--vz", dest="vv", type=float, default=None,
                              help="Velocity along the shaft [m/s] for ad hoc (default 0.0): "
                                   "climb/descent for a rotor, AIRSPEED for a propeller. "
                                   "Alternative to --jz/--muz/--alpha-rotor-deg.")
    axial_group.add_argument("--jz", dest="J_z", type=float, default=None,
                              help="AXIAL advance ratio, propeller convention: "
                                   "J_x = V_axial/(n*D). This is the classic J_x of propeller "
                                   "charts, and the one propulsive efficiency uses. Stored "
                                   "under the key J_z (disk axes). Alternative to --vz.")
    axial_group.add_argument("--muz", dest="mu_z", type=float, default=None,
                              help="AXIAL advance ratio, rotor convention: "
                                   "mu_x = V_axial/(Omega*R) = J_x/pi. Same number as "
                                   "lambda_z; stored under the key mu_z. Alternative to --vz.")
    axial_group.add_argument("--alpha-rotor-deg",
                              dest="disk_alpha_deg", type=float, default=None,
                              help="Disk angle [deg] ad hoc -- Vz is derived from mu_x/J_x "
                                   "and --rpm (required with this flag) + rotor radius of "
                                   "the project. Measured from the disk PLANE (90 deg is "
                                   "purely axial); for the propeller convention, measured "
                                   "from the shaft, use --alpha-disk-deg. Alternative to --vz. "
                                   "(--disk-alpha-deg is kept as an alias of this flag.)")
    p.add_argument("--collective", type=float, default=8.0, help="Collective pitch [deg] for ad hoc.")

    # --- Geometria (RotorGeometryDef) — Parte 3.3, grupo Geometria ---------
    p.add_argument("--geom-preset", choices=["rectangular", "tapered", "elliptic", "custom"],
                    default=None, help="Generate project.geometry from a parametric preset.")
    p.add_argument("--geom-file", metavar="PATH", default=None,
                    help="Load entire project.geometry from a .bemt (RotorGeometryDef).")
    p.add_argument("--geom-radius", type=float, default=None, help="radius_m.")
    p.add_argument("--geom-root-cutout", type=float, default=None, help="root_cutout_norm.")
    p.add_argument("--geom-n-blades", type=int, default=None, help="n_blades.")
    p.add_argument("--geom-chord", type=float, default=None,
                    help="constant chord_norm (rectangular preset).")
    p.add_argument("--geom-taper-ratio", type=float, default=None,
                    help="tip_chord_norm/root_chord_norm (tapered preset; requires --geom-chord "
                         "as root_chord_norm).")
    p.add_argument("--geom-max-chord", type=float, default=None,
                    help="max_chord_norm (elliptic preset).")
    p.add_argument("--geom-twist-root", type=float, default=None, help="twist_root_deg.")
    p.add_argument("--geom-twist-tip", type=float, default=None, help="twist_tip_deg.")
    p.add_argument("--geom-custom-points", metavar="r:c:t,r:c:t,...", default=None,
                    help="Point-by-point table (custom preset): r/R:chord_norm:twist_deg, "
                         "separated by comma.")

    # --- Airfoil (AirfoilDef) — Part 3.3 -------------------------------
    p.add_argument("--airfoil-source", choices=["analytical", "table"], default=None,
                    help="AirfoilDef.source.")
    p.add_argument("--airfoil-table", metavar="CSV", default=None,
                    help="Import a polar table (CSV) to AirfoilDef.table_slices "
                         "and set source='table' (same importer as airfoils.import_polar_csv).")
    p.add_argument("--dynamic-stall", dest="dynamic_stall", action="store_true", default=None,
                    help="AirfoilDef.use_dynamic_stall=True.")
    p.add_argument("--no-dynamic-stall", dest="dynamic_stall", action="store_false",
                    help="AirfoilDef.use_dynamic_stall=False.")
    # There is no flag for BEMTConfig.dynamic_stall_model: today only one
    # model is supported ("oye"), so the field has no real choice to
    # expose in the CLI -- what turns dynamic stall on/off is the boolean
    # --dynamic-stall/--no-dynamic-stall above. The field still exists
    # in BEMTConfig (serialized, used by the GUI); if a second model is
    # implemented, this is where the choice flag should be added back.
    p.add_argument("--airfoil-stall-model", choices=["linear", "clip", "enhanced", "viterna"],
                    default=None,
                    help="AirfoilDef.stall_model: shape of STATIC polar beyond stall. "
                         "'linear' keeps rising, 'clip'/'enhanced' plateau, 'viterna' "
                         "extends to full range (+/-180deg).")
    p.add_argument("--airfoil-sections-file", metavar="PATH", default=None,
                    help="Load project.airfoil_sections (multi-section) from a .bemt "
                         "(list of AirfoilDef).")

    # --- Config/Solver (BEMTConfig, stored in project.config) ------------
    p.add_argument("--inflow", default=None,
                    choices=["glauert_local", "glauert_global", "coleman_local", "coleman_global",
                             "drees_local", "drees_global", "pitt_peters_steady", "pitt_peters_unsteady"],
                    help="BEMTConfig.inflow_field_model.")
    p.add_argument("--prandtl-loss-mode", choices=["off", "tip", "root", "both"], default=None,
                    help="BEMTConfig.prandtl_loss_mode.")
    p.add_argument("--pitt-peters-states", type=int, choices=[3, 5], default=None,
                    help="BEMTConfig.pitt_peters_states.")
    p.add_argument("--pitt-peters-outer-iter", type=int, default=None,
                    help="BEMTConfig.pitt_peters_outer_iter.")
    p.add_argument("--pitt-peters-relax", type=float, default=None,
                    help="BEMTConfig.pitt_peters_relax.")
    p.add_argument("--pitt-peters-tol", type=float, default=None,
                    help="BEMTConfig.pitt_peters_tol.")
    p.add_argument("--rotational-augmentation", dest="rot_aug", action="store_true", default=None,
                    help="BEMTConfig.use_rotational_augmentation=True (Himmelskamp/Snel).")
    p.add_argument("--no-rotational-augmentation", dest="rot_aug", action="store_false",
                    help="BEMTConfig.use_rotational_augmentation=False.")
    p.add_argument("--radial-flow-correction", dest="radial_flow", action="store_true", default=None,
                    help="BEMTConfig.use_radial_flow_correction=True.")
    p.add_argument("--no-radial-flow-correction", dest="radial_flow", action="store_false",
                    help="BEMTConfig.use_radial_flow_correction=False.")
    p.add_argument("--solver", choices=["fixed_point", "newton", "bisection", "aitken"], default=None,
                    help="BEMTConfig.solver.")
    p.add_argument("--max-iter", type=int, default=None, help="BEMTConfig.max_iter.")
    p.add_argument("--tol", type=float, default=None, help="BEMTConfig.tol.")
    p.add_argument("--relax", type=float, default=None, help="BEMTConfig.relax.")
    p.add_argument("--relax-schedule", dest="relax_schedule", action="store_true", default=None,
                    help="BEMTConfig.relax_schedule=True.")
    p.add_argument("--no-relax-schedule", dest="relax_schedule", action="store_false",
                    help="BEMTConfig.relax_schedule=False.")

    # --- Export ---------------------------------------------------------
    p.add_argument("--outdir", default=None,
                    help="Output folder. Default: <project>/batch.outdir if defined, "
                         "otherwise <project>/outputs.")
    p.add_argument("--plots", nargs="*", default=None,
                    help="Which plots to export (e.g. performance disk_map). Default: "
                         "batch.plots from the selected batch, or the project's. "
                         "'--plots' without values = no plots.")
    p.add_argument("--no-csv", action="store_true", help="Do not write results.csv.")
    p.add_argument("--report", nargs="?", const="", default=None, metavar="FILE",
                    help="Generate a self-contained HTML report (summary table + mesh, "
                         "solver and rotor used + embedded plots). Without value, "
                         "write <outdir>/report.html. Same report as the "
                         "'Generate report...' button in the GUI.")
    p.add_argument("--report-notes", default=None, metavar="TEXT",
                    help="Notes text to embed in the report (--report).")
    p.add_argument("--export-layout", choices=["flat", "per_case"], default="flat",
                    help="Organization of PER-CONDITION plots (docs/plano_v3.md Part 4.3): "
                         "'flat' (default) = one file per case, self-explanatory name; "
                         "'per_case' = one folder per case.")

    # --- generic setter (S3, docs/production-plan.md) --------------------
    # Only 14/40 BEMTConfig fields and 3/25 AirfoilDef fields had a
    # dedicated flag; creating ~50 new flags would make --help unreadable
    # and become a list that's easy to let drift. --set closes the gap
    # without that: any BEMTConfig/AirfoilDef/RotorGeometryDef field
    # becomes reachable, validated against the dataclass's real fields
    # (dataclasses.fields) and converted from its type annotation
    # (int/float/bool/str).
    p.add_argument(
        "--set", dest="set", action="append", default=[],
        metavar="NAMESPACE.FIELD=VALUE",
        help="Set any field of BEMTConfig/AirfoilDef/RotorGeometryDef directly, "
             "without needing a dedicated flag. NAMESPACE is 'config' (BEMTConfig, e.g. "
             "config.Ne=90, config.Npsi=144, config.rho=1.2, config.is_propeller=true), "
             "'airfoil' (AirfoilDef, e.g. airfoil.cd0=0.012) or 'geom' (RotorGeometryDef, "
             "e.g. geom.n_blades=3). Bool accepts true/false/1/0/yes/no. Repeatable "
             "(--set a=1 --set b=2). PRECEDENCE: --set is applied AFTER all dedicated "
             "flags above (--inflow, --geom-radius, --dynamic-stall, etc.), so in case "
             "of conflict --set always wins. Non-existent field name or value that does "
             "not convert to the field type is an error (SystemExit), never silently applied.")

    trim_group = p.add_argument_group("Trimmed run (fixed thrust/CT, bisection loop)")
    trim_group.add_argument(
        "--trim-mode", choices=["solve_rpm", "solve_collective"], default=None,
        help="Instead of running the condition as entered, solve for one DOF by bisection until "
             "a target thrust/CT is hit: 'solve_rpm' keeps --collective fixed and solves for RPM; "
             "'solve_collective' keeps --rpm fixed and solves for collective. Requires at least one "
             "condition to run (ad hoc, a saved case, or a batch) and exactly one of "
             "--trim-target-thrust/--trim-target-ct. For a batch, every queued "
             "condition is trimmed independently.")
    trim_target_group = trim_group.add_mutually_exclusive_group()
    trim_target_group.add_argument("--trim-target-thrust", type=float, default=None,
                                    help="Target Thrust [N] for --trim-mode.")
    trim_target_group.add_argument("--trim-target-ct", type=float, default=None,
                                    help="Target CT [-] for --trim-mode.")

    p.add_argument("--validate-only", action="store_true",
                    help="Only validate the project and flight condition, do not run the engine. "
                         "Useful before launching a long batch without supervision.")
    p.add_argument("--ignore-validation-errors", action="store_true",
                    help="Run even with validation errors (default is to abort). "
                         "Warnings never block.")

    return p


def _preprocess_argv(argv=None) -> list[str]:
    """Normalizes `argv` before parsing: `--alpha-range VAL` becomes
    `--alpha-range=VAL` so argparse isn't confused when VAL starts
    with `-` (e.g. negative ranges, "-10:20:0.5")."""
    if argv is None:
        argv = sys.argv[1:]
    else:
        argv = list(argv)

    new_argv = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--alpha-range" and i + 1 < len(argv):
            new_argv.append(f"--alpha-range={argv[i+1]}")
            i += 2
        else:
            new_argv.append(arg)
            i += 1
    return new_argv


def _parse_args(argv=None) -> argparse.Namespace:
    return _build_parser().parse_args(_preprocess_argv(argv))


def _build_run_options_dataclass(parser: argparse.ArgumentParser):
    """Derives a dataclass with one field per parser flag (same `dest`,
    same default), so that `RunOptions` can never diverge from the
    argparse's real flags."""
    fields = []
    seen = set()
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        dest = action.dest
        if dest == argparse.SUPPRESS or dest in seen:
            continue
        seen.add(dest)
        default = action.default
        # dataclasses rejects a mutable default (list/dict/set) directly --
        # e.g. `--set` (action="append", default=[]). default_factory
        # captures the value by copy so instances don't share the same list.
        if isinstance(default, (list, dict, set)):
            fields.append((dest, typing.Any,
                            dataclasses.field(default_factory=lambda d=default: type(d)(d))))
        else:
            fields.append((dest, typing.Any, dataclasses.field(default=default)))
    return dataclasses.make_dataclass("RunOptions", fields)


RunOptions = _build_run_options_dataclass(_build_parser())


def _run_options_from_argv(cls, argv=None):
    ns = _parse_args(argv)
    return cls(**{f.name: getattr(ns, f.name) for f in dataclasses.fields(cls)})


RunOptions.from_argv = classmethod(_run_options_from_argv)


# =============================================================================
# Applying flags to the Project (Geometry/Airfoil/Config-Solver group —
# Part 3.3, item 3: setting via command line any field that today is only
# editable from the GUI)
# =============================================================================

def _apply_geometry_flags(project, args) -> None:
    g = project.geometry

    # `--geom-file` used to sit in an `elif` AFTER all the presets, so
    # `--geom-preset X --geom-file Y` used the preset and silently
    # discarded the file. There is no obvious answer for which should win, so
    # the right move is to reject the combination rather than pick one on our own.
    if args.geom_preset and args.geom_file:
        raise SystemExit(
            "cli.py: --geom-preset and --geom-file are mutually exclusive "
            "(both define the entire geometry). Choose one.")

    if args.geom_preset == "rectangular":
        project.geometry = geometry.generate_rectangular(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            chord_norm=args.geom_chord if args.geom_chord is not None else 0.08,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 12.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 4.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "tapered":
        root_chord = args.geom_chord if args.geom_chord is not None else 0.10
        tip_chord = root_chord * args.geom_taper_ratio if args.geom_taper_ratio is not None else 0.04
        project.geometry = geometry.generate_tapered(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            root_chord_norm=root_chord, tip_chord_norm=tip_chord,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 14.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 2.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "elliptic":
        project.geometry = geometry.generate_elliptic(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            max_chord_norm=args.geom_max_chord if args.geom_max_chord is not None else 0.10,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 14.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 2.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "custom":
        if not args.geom_custom_points:
            raise SystemExit("--geom-preset custom requires --geom-custom-points r:c:t,...")
        r_norm, chord_norm, twist_deg = [], [], []
        for point in args.geom_custom_points.split(","):
            r, c, t = point.split(":")
            r_norm.append(float(r)); chord_norm.append(float(c)); twist_deg.append(float(t))
        project.geometry = geometry.generate_custom(
            r_norm, chord_norm, twist_deg,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_file:
        from .models import load_bemt
        project.geometry = load_bemt(RotorGeometryDef, args.geom_file)
    else:
        # no preset/file: only overrides loose scalar fields, if given
        if args.geom_radius is not None:
            g.radius_m = args.geom_radius
        if args.geom_root_cutout is not None:
            g.root_cutout_norm = args.geom_root_cutout
        if args.geom_n_blades is not None:
            g.n_blades = args.geom_n_blades


def _apply_airfoil_flags(project, args) -> None:
    a = project.airfoil
    if args.airfoil_source is not None:
        a.source = args.airfoil_source
    if args.airfoil_table:
        a.table_slices = airfoils.import_polar_csv(args.airfoil_table)
        a.source = "table"
    if args.dynamic_stall is not None:
        a.use_dynamic_stall = args.dynamic_stall
    if args.airfoil_stall_model is not None:
        a.stall_model = args.airfoil_stall_model
    if args.airfoil_sections_file:
        from .models import load_bemt_list
        project.airfoil_sections = load_bemt_list(AirfoilDef, args.airfoil_sections_file)


def _apply_config_flags(project, args) -> None:
    cfg = project.config   # dict (asdict de BEMTConfig)
    simple_map = {
        "inflow": "inflow_field_model",
        "prandtl_loss_mode": "prandtl_loss_mode",
        "pitt_peters_states": "pitt_peters_states",
        "pitt_peters_outer_iter": "pitt_peters_outer_iter",
        "pitt_peters_relax": "pitt_peters_relax",
        "pitt_peters_tol": "pitt_peters_tol",
        "solver": "solver",
        "max_iter": "max_iter",
        "tol": "tol",
        "relax": "relax",
    }
    for arg_name, cfg_key in simple_map.items():
        val = getattr(args, arg_name)
        if val is not None:
            cfg[cfg_key] = val
    if args.rot_aug is not None:
        cfg["use_rotational_augmentation"] = args.rot_aug
    if args.radial_flow is not None:
        cfg["use_radial_flow_correction"] = args.radial_flow
    if args.relax_schedule is not None:
        cfg["relax_schedule"] = args.relax_schedule


# =============================================================================
# generic --set (S3, docs/production-plan.md) -- closes the parity gap
# without creating ~50 new dedicated flags. See --set's help in _build_parser.
# =============================================================================

# namespace -> (attribute on Project, dataclass used to validate field/type)
_SET_NAMESPACE_DATACLASS = {
    "config": BEMTConfig,
    "airfoil": AirfoilDef,
    "geom": RotorGeometryDef,
}

_TRUE_STRINGS = {"true", "1", "yes"}
_FALSE_STRINGS = {"false", "0", "no"}


def _unwrap_optional(py_type):
    """`Optional[X]` (== `Union[X, None]`) -> X; any other type, unchanged."""
    if typing.get_origin(py_type) is typing.Union:
        args = [a for a in typing.get_args(py_type) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return py_type


def _convert_set_value(raw_value: str, py_type, field_name: str):
    py_type = _unwrap_optional(py_type)
    if py_type is bool:
        low = raw_value.strip().lower()
        if low in _TRUE_STRINGS:
            return True
        if low in _FALSE_STRINGS:
            return False
        raise ValueError(
            f"invalid boolean value {raw_value!r} for '{field_name}' "
            f"(use true/false/1/0/yes/no).")
    if py_type is int:
        try:
            return int(raw_value)
        except ValueError:
            raise ValueError(f"invalid integer value {raw_value!r} for '{field_name}'.")
    if py_type is float:
        try:
            return float(raw_value)
        except ValueError:
            raise ValueError(f"invalid numeric value {raw_value!r} for '{field_name}'.")
    if py_type is str:
        return raw_value
    raise ValueError(
        f"field '{field_name}' has type {py_type!r}, not supported by --set "
        f"(lists/dicts are not convertible from a string; use --geom-file/"
        f"--airfoil-sections-file/--airfoil-table for such fields).")


def _apply_set_flags(project, args) -> None:
    """Applies all --set flags, AFTER the dedicated flags (precedence
    documented in --help): in case of conflict, --set wins."""
    if not args.set:
        return

    type_hints_cache: dict = {}
    for item in args.set:
        if "=" not in item:
            raise SystemExit(
                f"--set: invalid format {item!r}, expected NAMESPACE.FIELD=VALUE "
                f"(e.g. --set config.Ne=90).")
        key, raw_value = item.split("=", 1)
        if "." not in key:
            raise SystemExit(
                f"--set: {key!r} needs a namespace (config./airfoil./geom.), "
                f"e.g. --set config.{key}=...")
        ns, field_name = key.split(".", 1)
        dataclass_type = _SET_NAMESPACE_DATACLASS.get(ns)
        if dataclass_type is None:
            raise SystemExit(
                f"--set: invalid namespace {ns!r}. Valid: "
                f"{', '.join(sorted(_SET_NAMESPACE_DATACLASS))}.")

        valid_fields = {f.name for f in dataclasses.fields(dataclass_type)}
        if field_name not in valid_fields:
            raise SystemExit(
                f"--set: field '{ns}.{field_name}' does not exist in "
                f"{dataclass_type.__name__}. Valid fields: "
                f"{', '.join(sorted(valid_fields))}.")

        if dataclass_type not in type_hints_cache:
            type_hints_cache[dataclass_type] = typing.get_type_hints(dataclass_type)
        py_type = type_hints_cache[dataclass_type][field_name]

        try:
            value = _convert_set_value(raw_value, py_type, field_name)
        except ValueError as exc:
            raise SystemExit(f"--set: {exc}")

        if ns == "config":
            project.config[field_name] = value           # dict (asdict of BEMTConfig)
        elif ns == "airfoil":
            setattr(project.airfoil, field_name, value)
        elif ns == "geom":
            setattr(project.geometry, field_name, value)


# =============================================================================
# NeuralFoil (Phase 7 -- Part 7.4): polar table generation, CLI mode
# =============================================================================

def _parse_float_list(text: str, flag: str) -> list[float]:
    try:
        return [float(v) for v in text.split(",") if v.strip()]
    except ValueError as exc:
        raise ValueError(f"Invalid value in {flag}={text!r}: {exc}") from exc


def _run_gen_neuralfoil(project, project_path, args) -> int:
    if not args.airfoil_geometry:
        print("Error: --gen-neuralfoil requires --airfoil-geometry (NACA4/5 code or preset).",
              file=sys.stderr)
        return 2
    if not args.reynolds or not args.mach:
        print("Error: --gen-neuralfoil requires --reynolds and --mach (at least one value each).",
              file=sys.stderr)
        return 2

    try:
        geom = airfoils.resolve_geometry_spec(args.airfoil_geometry)
        reynolds_list = _parse_float_list(args.reynolds, "--reynolds")
        mach_list = _parse_float_list(args.mach, "--mach")
        lo_s, hi_s, step_s = args.alpha_range.split(":")
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    try:
        slices = api.run_external_polar_from_geometry(
            geom, engine="neuralfoil",
            reynolds_list=reynolds_list, mach_list=mach_list,
            alpha_min_deg=float(lo_s), alpha_max_deg=float(hi_s), alpha_step_deg=float(step_s),
        )
    except (RuntimeError, ValueError) as exc:
        # Clear message (not a raw traceback) -- covers the common case of
        # 'neuralfoil' not being installed in this environment.
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"NeuralFoil: {len(slices)} polar(s) generated for {args.airfoil_geometry!r} "
          f"({len(reynolds_list)} Reynolds x {len(mach_list)} Mach).")

    if args.export_table:
        out = api.export_polar_table(slices, args.export_table)
        print(f"Table exported to {out}")
    else:
        project.airfoil.table_slices.extend(slices)
        project.airfoil.source = "table"
        api.save_project(project)
        print(f"Applied to project.airfoil.table_slices and saved to {project_path}.")
    return 0


# =============================================================================
# main
# =============================================================================

def main(argv=None, options=None) -> int:
    # If called with no arguments (argv=None and sys.argv empty), inject a default.
    # This allows running as "python zbemt/cli.py" and getting useful behavior
    # without breaking usage with explicit argv or RunOptions.
    if argv is None and options is None and len(sys.argv) == 1:
        argv = ["--project", DEFAULT_PROJECT_PATH,
                "--rpm", str(DEFAULT_RPM), "--validate-only"]

    args = options if options is not None else RunOptions.from_argv(argv)

    if args.new:
        project = api.new_project(args.new, name=args.name)
        project_path = args.new
    else:
        project = api.open_project(args.project)
        project_path = args.project

    if args.list_batches:
        # A sweep batch stores `sweep_params`, not a list of conditions --
        # printing `len(conditions)` said "0 condition(s)" for all of
        # them, which sounded like an empty batch. What matters here is
        # how many cases the sweep WILL generate.
        for b in project.batches:
            if b.conditions:
                quanto = f"{len(b.conditions)} explicit condition(s)"
            else:
                params = b.sweep_params or {}
                if b.sweep_kind == "factorial":
                    # Factorial: the product of the axes, not the number of axes.
                    eixos = [eixo.get("values", []) for eixo in params.get("axes", [])]
                else:
                    eixos = [v for v in params.values() if isinstance(v, (list, tuple))]
                n = 1
                for eixo in eixos:
                    n *= max(len(eixo), 1)
                quanto = (f"{n} sweep case(s)" if eixos
                          else "no conditions defined")
            print(f"{b.name}\t{quanto}\tsweep_kind={b.sweep_kind}")
        return 0
    if args.list_cases:
        for c in project.saved_cases:
            print(f"{c.name}\tmu={c.mu_x}\tcollective_deg={c.collective_deg}\tVv={c.Vz}\trpm={c.rpm}")
        return 0

    if args.gen_neuralfoil:
        return _run_gen_neuralfoil(project, project_path, args)

    _apply_geometry_flags(project, args)
    _apply_airfoil_flags(project, args)
    _apply_config_flags(project, args)
    _apply_set_flags(project, args)   # AFTER the dedicated ones -- --set wins on conflict

    if args.save_as:
        project.path = args.save_as
        api.save_project(project)
        project_path = args.save_as

    # --- resolve what to run: saved batch > saved case > existing
    # batch.conditions > ad hoc condition (parity Part 3.3, item 1-2) -----
    # The two angles are in different exclusive GROUPS (the axis one is
    # the in-plane component; the disk one, the axial), so `argparse`
    # cannot express "one from each group, except this combination".
    # Without the explicit check, `--alpha-disk-deg 6 --alpha-rotor-deg 84`
    # used to pass and resolve Vz from a still-zero mu_x: Vz=0, a silent
    # hover condition instead of the requested cruise.
    if args.alpha_disk_deg is not None and args.disk_alpha_deg is not None:
        print("cli.py: error: --alpha-disk-deg and --alpha-rotor-deg are the "
              "same angle written two ways (alpha_disk = 90 - alpha_rotor): with "
              "both, neither velocity component sets the scale. Give one angle "
              "plus a dimensional or non-dimensional component "
              "(--vz/--jz/--muz for the axial one, --mux/--jx for the in-plane).",
              file=sys.stderr)
        return 2

    if args.from_bemt_batch:
        batch = api.get_batch(project, args.from_bemt_batch)
    elif args.from_bemt_case:
        case = api.get_saved_case(project, args.from_bemt_case)
        batch = BatchDefinition(name=f"cli_case_{case.name}", conditions=[case])
    else:
        raio_m = project.geometry.radius_m

        def _axial(mu_conhecido: float):
            """Axial component [m/s]. Only the disk-angle branch depends
            on the already-resolved in-plane component."""
            if args.disk_alpha_deg is not None:
                if args.rpm is None:
                    return None, ("cli.py: error: --alpha-rotor-deg requires --rpm "
                                  "(Vz is derived from mu_x/J_x, rpm and rotor radius).")
                return api.vv_from_alpha_deg(args.disk_alpha_deg, mu_conhecido,
                                              args.rpm, raio_m), None
            if args.J_z is not None or args.mu_z is not None:
                if args.rpm is None:
                    return None, ("cli.py: error: --jz/--muz require --rpm "
                                  "(the axial speed is mu_x*Omega*R, and Omega comes "
                                  "from the RPM).")
                mu_x = api.J_to_mu(args.J_z) if args.J_z is not None else args.mu_z
                return api.mu_to_V(mu_x, args.rpm, raio_m), None
            if args.vv is not None:
                return args.vv, None
            return 0.0, None

        # ORDER: normally the in-plane component is the known one and the
        # axial one can be derived from it (--alpha-rotor-deg). With
        # --alpha-disk-deg the dependency inverts -- the in-plane comes out
        # of the axial -- so the axial comes first. Same inversion as
        # `bemt.resolve_advance_velocity`.
        if args.alpha_disk_deg is not None:
            if args.rpm is None:
                print("cli.py: error: --alpha-disk-deg requires --rpm "
                      "(the in-plane component is tan(alpha_disk)*Vz, and mu_x needs Omega*R).",
                      file=sys.stderr)
                return 2
            Vz, erro = _axial(0.0)
            if erro:
                print(erro, file=sys.stderr)
                return 2
            # |Vz|: same reason as `bemt.resolve_advance_velocity`.
            mu_x = api.V_to_mu(
                float(np.tan(np.deg2rad(args.alpha_disk_deg))) * abs(Vz),
                args.rpm, raio_m)
        else:
            if args.mu_x is not None:
                mu_x = args.mu_x
            elif args.J_x is not None:
                mu_x = api.J_to_mu(args.J_x)
            else:
                mu_x = 0.0   # default: hover
            Vz, erro = _axial(mu_x)
            if erro:
                print(erro, file=sys.stderr)
                return 2

        condition = FlightCondition(
            name="cli", rpm=args.rpm, mu_x=mu_x, Vz=Vz,
            collective_deg=args.collective,
        )
        batch = BatchDefinition(name="cli_adhoc", conditions=[condition])

    # Validation BEFORE running: without this, a configuration the solver
    # rejects (unimplemented inflow, pitt_peters_states=5, source
    # 'external') only failed deep inside, with a raw traceback, possibly
    # after hours of unsupervised batch. `api.validate_project` already
    # existed exactly for this and the CLI never called it.
    issues = api.validate_project(project, conditions=batch.conditions)
    erros = [i for i in issues if i.level == "error"]
    if issues:
        destino = sys.stderr if erros else sys.stdout
        print("Project validation:", file=destino)
        for issue in issues:
            print(f"  {issue}", file=destino)
    if erros and not args.ignore_validation_errors:
        print(f"\ncli.py: {len(erros)} validation error(s) — nothing was run.\n"
              f"Use --ignore-validation-errors to run anyway.", file=sys.stderr)
        return 2

    if args.validate_only:
        print("\n--validate-only: project verified, nothing was run.")
        return 0

    if args.trim_mode is not None:
        if args.trim_target_thrust is None and args.trim_target_ct is None:
            print("cli.py: error: --trim-mode requires --trim-target-thrust or --trim-target-ct.",
                  file=sys.stderr)
            return 2
        target_kind = "thrust" if args.trim_target_thrust is not None else "CT"
        target_value = args.trim_target_thrust if args.trim_target_thrust is not None else args.trim_target_ct
        try:
            results = api.run_batch(project, batch, trim_mode=args.trim_mode,
                                    target_kind=target_kind, target_value=target_value)
        except ValueError as exc:
            print(f"cli.py: error: {exc}", file=sys.stderr)
            return 2
    else:
        results = api.run_batch(project, batch)

    # `batch` here may be a NAMED batch (--from-bemt-batch) or the ad hoc
    # one built above, either of which may carry its own outdir/plots.
    outdir = args.outdir or batch.outdir or str(Path(project_path) / "outputs")
    # `--plots` with no values (nargs="*") becomes [], which is not None
    # and therefore SUPPRESSED the project's plots instead of falling back
    # to the default. An explicit empty list now means "no plots", and the
    # flag's absence still means "use what the project asked for".
    if args.plots is None:
        plots = batch.plots or None
    else:
        plots = args.plots or None

    written = api.export_results(results, outdir=outdir, plots=plots,
                                  save_csv=not args.no_csv, project=project,
                                  layout=args.export_layout)

    # The report uses the plots that apply to the selection (default of
    # `api.generate_report`), regardless of `--plots`: `--plots` controls
    # what ends up on disk as standalone PNGs, `--report` controls what
    # gets embedded in the HTML. Passing an empty `--plots` to save files
    # should not empty out the report.
    if args.report is not None:
        report_path = args.report or str(Path(outdir) / "report.html")
        written.append(str(api.generate_report(
            results, report_path, project=project,
            title=f"zBEMT Report — {project.name}",
            notes=args.report_notes)))

    # Both coefficient families are always in `summary` (see
    # `bemt.aggregate_results`); what changes is which one the user wants
    # to read. Printing FM for a propeller is worse than useless: FM is the
    # figure of merit for HOVER, and an aircraft propeller never hovers --
    # the number comes out low and looks like a bad design, when the
    # metric simply does not apply. The one that fills this role on the
    # propeller side is `eta_prop`.
    if project.config.get("is_propeller"):
        campos = ("J_z", "CT_prop", "CQ_prop", "CP_prop", "eta_prop")
    else:
        campos = ("CT", "CQ", "CP", "FM")

    for res in results:
        summary = res.summary
        keys = [k for k in campos if k in summary]
        parts = ", ".join(f"{k}={summary[k]:.5g}" for k in keys)
        print(f"[{res.condition_name}] {parts}")

    if written:
        print("Files generated:")
        for w in written:
            print(f"  {w}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
