"""Implement the command-line interface for the same workflows as the GUI.

Purpose: parse project, geometry, airfoil, flight-condition, batch, solver, and
export options and delegate all behavior to ``api.py``. Inputs are arguments,
project files, and optional ``--set`` paths. Outputs are validation messages,
results, saved projects, tables, figures, and reports. This module contains no
physics and no independent serialization; axis labels and keys follow
``nomenclature.py``. CLI limitations are the options exposed by the parser and
the physical limitations reported by the selected models.

cli.py
======

Script/CLI equivalent to the GUI. Same ``api.py`` calls that
``zbemt.gui.app`` uses. Zero widgets, zero physics, zero direct I/O.
Everything goes through ``api.py``.

CLI<->GUI<->.bemt parity: every flag of this script sets a
``Project``/``BEMTConfig`` field that is also editable from the GUI, and
every ``.bemt`` file generated by any of the three paths (GUI, CLI,
manual editing) is read back identically by the other two.

Two equivalent ways to use it (every command-line flag has a
corresponding Python field in ``RunOptions``, and vice versa):

    from zbemt.cli import main, RunOptions
    main(["--project", "projects/MyProject", "--rpm", "300"])
    main(options=RunOptions(project="projects/MyProject", rpm=300.0))

Typical command-line usage (``zbemt`` is the installed entry point;
``python -m zbemt.cli`` works identically):

    zbemt --project projects/MyProject
    zbemt --project projects/MyProject --from-bemt-batch hover_sweep
    zbemt --project projects/MyProject --list-batches
    zbemt --new projects/MyProject --radius 0.6 --rpm 1200 \\
        --inflow pitt_peters_steady --dynamic-stall --save-as projects/MyProject
    zbemt --project projects/MyProject \\
        --gen-neuralfoil --airfoil-geometry naca2412 \\
        --reynolds 1e5,5e5,1e6 --mach 0.1,0.3 --alpha-range -10:20:0.5 \\
        --export-table saida/naca2412_neuralfoil.csv
    zbemt --project projects/MyProject --gen-xfoil \\
        --airfoil-geometry naca2412 --reynolds 1e6 --mach 0.3
    zbemt --project projects/MyProject --compare projects/RotorA,projects/RotorB
    zbemt --project projects/MyProject --optimize tip_chord_study --max-evals 60
    zbemt --project projects/MyProject --optimize pareto_study --algorithm nsga2
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
import typing
from pathlib import Path

import numpy as np

# Running the FILE directly (`python zbemt/cli.py`, or the "Run" button of
# an IDE with this file open) executes it as a standalone script, without a
# package. Then every `from . import ...` below raises
# "attempted relative import with no known parent package". Putting the
# repository root on `sys.path` and declaring `__package__` makes the
# relative import resolve, so the "Run" button works the same as
# `python -m zbemt.cli`. Outside that case (normal import, `-m`), this
# block does not run and nothing changes.
if __name__ == "__main__" and __package__ in (None, ""):    # pragma: no cover
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    __package__ = "zbemt"

from . import api
from . import nomenclature
from .models import FlightCondition, BatchDefinition, RotorGeometryDef, AirfoilDef
from . import geometry
from . import airfoils
from .bemt import BEMTConfig


# Running with no arguments (for example, the IDE's "Run" button) uses this example
# project by default.
DEFAULT_PROJECT_PATH = "projects/starter_rotor"

#: RPM for the no-argument run. Must be explicit here: RPM is MANDATORY in
#: every flight condition (`studies._require_rpm` has no default, on
#: purpose, because BEMT non-dimensionalizes everything by Omega*R) and
#: `starter_rotor` ships no saved cases. Without this, the no-argument
#: run used to end in a validation ERROR ("Flight condition without
#: RPM") instead of a clean run. That is a terrible first impression for
#: someone who just hit "Run" to see what the program does.
DEFAULT_RPM = 600.0


# =============================================================================
# Argument parsing
#
# Two ways to set this script's options (requested by the project owner:
# "every command-line flag must also be settable directly in Python"):
#
#   from zbemt.cli import main, RunOptions
#   main(["--project", "projects/X", "--rpm", "300", "--mu-inplane", "0.2"])
#   main(options=RunOptions(project="projects/X", rpm=300.0, mu_inplane=0.2))
#
# `RunOptions` is generated from the argparse.ArgumentParser itself (via
# `_build_run_options_dataclass`), so the two forms can never diverge:
# every flag defined in `_build_parser` automatically becomes a
# `RunOptions` field with the same default, and there is no way to add a
# flag without the corresponding Python field (or vice versa).
# =============================================================================

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Run a new or existing zBEMT project without the GUI, "
                     "through api.py. The CLI has full parity with the GUI "
                     "(docs/parity_registry.md).",
    )
    project_group = p.add_mutually_exclusive_group(required=True)
    project_group.add_argument("--project", metavar="PATH",
                                help="Open an existing project in this folder.")
    project_group.add_argument("--new", metavar="PATH",
                                help="Create a new project (default geometry/airfoil) in this folder.")

    p.add_argument("--name", default=None,
                    help="Project name, used only with --new (default: folder name).")
    p.add_argument("--save-as", metavar="PATH", default=None,
                    help="Save the project in this folder before running, with every "
                         "field set by the flags below already applied. If you omit it, zBEMT "
                         "does not write the flags to disk, and they affect this call only.")

    # --- listing/selecting saved batches and cases (Part 3.3, item 1-2) --
    p.add_argument("--list-batches", action="store_true",
                    help="List saved batches in project.batches and exit.")
    p.add_argument("--list-cases", action="store_true",
                    help="List saved cases in project.saved_cases and exit.")
    p.add_argument("--from-bemt-batch", metavar="NAME", default=None,
                    help="Run the saved batch NAME (project.batches) instead of creating "
                         "an ad hoc condition.")
    p.add_argument("--from-bemt-case", metavar="NAME", default=None,
                    help="Run the saved case NAME (project.saved_cases).")

    # --- External polar table generation (Phase 7, docs/plano_v3.md
    # Part 7.4). Mode independent of running BEMT, exits right after
    # generating (and optionally exporting/applying). One flag per
    # engine; every other option of the group is shared. ---------------
    polar_group = p.add_argument_group("External polar table generation")
    polar_group.add_argument(
        "--gen-neuralfoil", action="store_true",
        help="Generate a polar table via NeuralFoil for --airfoil-geometry and exit "
             "(does not run BEMT). Requires the 'neuralfoil' package (pip install neuralfoil).")
    polar_group.add_argument(
        "--gen-xfoil", action="store_true",
        help="Generate a polar table via XFOIL for --airfoil-geometry and exit "
             "(does not run BEMT). Shares every option of this group with "
             "--gen-neuralfoil. Only the engine differs. The three transition "
             "options below apply to XFOIL only. Stops with an error "
             "when XFOIL support is not available.")
    polar_group.add_argument(
        "--airfoil-geometry", metavar="SPEC", default=None,
        help="Airfoil geometry: a NACA 4-digit or 5-digit code (for example "
             "'naca2412', 'naca23012') "
             f"or a typical rotor-blade preset ({', '.join(sorted(airfoils.AIRFOIL_PRESETS))}).")
    polar_group.add_argument(
        "--reynolds", metavar="R1,R2,...", default=None,
        help="List of Reynolds for the sweep, for example '1e5,5e5,1e6'.")
    polar_group.add_argument(
        "--mach", metavar="M1,M2,...", default=None,
        help="List of Mach for the sweep, for example '0.1,0.3'.")
    polar_group.add_argument(
        "--alpha-range", metavar="MIN:MAX:STEP", default="-10:20:0.5",
        help="Alpha [deg] range for the sweep (default: -10:20:0.5).")
    polar_group.add_argument(
        "--export-table", metavar="PATH", default=None,
        help="Write the generated polar table to PATH (CSV, import format). "
             "If omitted, the table is appended to project.airfoil.table_slices and the project "
             "is saved (equivalent to applying directly from GUI).")
    polar_group.add_argument(
        "--ncrit", type=float, metavar="FLOAT", default=None,
        help="XFOIL only (--gen-xfoil): critical amplification factor N of the "
             "e^N transition criterion. A lower N predicts earlier transition and "
             "a more conservative drag level (default: 9). The option is rejected "
             "together with --gen-neuralfoil.")
    polar_group.add_argument(
        "--xtr-top", type=float, metavar="FLOAT", default=None,
        help="XFOIL only (--gen-xfoil): chord fraction where transition is forced "
             "on the upper surface, in (0, 1]. A value of 1 leaves free transition "
             "(default: 1). The option is rejected together with --gen-neuralfoil.")
    polar_group.add_argument(
        "--xtr-bot", type=float, metavar="FLOAT", default=None,
        help="XFOIL only (--gen-xfoil): chord fraction where transition is forced "
             "on the lower surface, in (0, 1]. A value of 1 leaves free transition "
             "(default: 1). The option is rejected together with --gen-neuralfoil.")

    # --- Design tools: geometry comparison and saved optimization
    # studies. Same early-exit pattern as the group above: they never
    # reach the BEMT batch below. --------------------------------------
    design_group = p.add_argument_group("Design tools")
    design_group.add_argument(
        "--compare", metavar="PROJECTS", default=None,
        help="Compare blade geometries and exit (no batch is run). PROJECTS is a "
             "comma-separated list of other project folders. Each folder becomes one "
             "geometry variant, named after its folder, and the geometry of --project "
             "joins the comparison as the variant named 'base'. Every variant runs the "
             "saved cases of --project. When there are none, pass --rpm to compare at "
             "one default condition. Writes comparison.html and comparison.csv to "
             "the outputs folder of --project.")
    design_group.add_argument(
        "--optimize", nargs="?", const="", default=None, metavar="NAME",
        help="Run one saved optimization study and exit (no batch is run). NAME selects "
             "an entry of project.optimizations by name. Without NAME, the first entry "
             "runs. A study with two objectives, or with algorithm nsga2/de, runs the "
             "Pareto search and writes an HTML report, the front CSV and the "
             "evaluations CSV; otherwise the derivative-free search writes its report "
             "plus a history CSV. Everything lands in the outputs folder.")
    design_group.add_argument(
        "--algorithm", choices=["powell", "nelder-mead", "de", "nsga2"],
        default=None,
        help="Search used by --optimize, overriding the value stored in the study. "
             "nsga2 evolves a Pareto front; de is a global single-result search; "
             "powell and nelder-mead stay derivative-free single-objective.")
    design_group.add_argument(
        "--population", type=int, default=None, metavar="N",
        help="Population of the evolutionary searches (--optimize with nsga2 or de), "
             "overriding the value stored in the study.")
    design_group.add_argument(
        "--generations", type=int, default=None, metavar="N",
        help="Generations of the evolutionary searches, overriding the value stored "
             "in the study.")
    design_group.add_argument(
        "--seed", type=int, default=None, metavar="N",
        help="Seed of the evolutionary searches; the same seed reproduces the same "
             "search.")
    design_group.add_argument(
        "--workers", type=int, default=None, metavar="N",
        help="Evaluation processes requested for the evolutionary searches. Stored "
             "on the study. Each generation is spread over that many "
             "processes, so the wall time falls almost in proportion "
             "until there are more workers than cores.")
    design_group.add_argument(
        "--pareto-csv", metavar="PATH", default=None,
        help="Destination of the Pareto front CSV written by --optimize when the run "
             "is multi-objective. Without it, the file lands beside the report under "
             "the study's own name.")
    design_group.add_argument(
        "--max-evals", type=int, default=None, metavar="N",
        help="Evaluation limit used by --optimize, overriding the value stored in the "
             "study definition. Without this flag, the stored value is kept.")
    design_group.add_argument(
        "--trim", choices=["none", "thrust", "CT"], default="none",
        help="Loading held constant across the --compare variants, so efficiency "
             "is compared at equal loading. 'thrust' or 'CT' reads the target from the "
             "first variant (the reference: the geometry of --project, named 'base') "
             "and, at every condition, trims each other variant to it. Propellers "
             "solve RPM, and rotors solve collective. Trimmed summaries record "
             "the columns trim_target, trim_dof and trim_dof_value. Each trimmed "
             "case bisects one control and costs roughly ten times a direct "
             "solve. With the default none, every variant runs the same controls.")

    # --- Transient maneuvers (SC-12) -------------------------------------
    maneuver_group = p.add_argument_group("Transient maneuver (SC-12)")
    maneuver_group.add_argument(
        "--maneuver", nargs="?", const="", default=None, metavar="NAME",
        help="March one saved trajectory and exit (no batch is run). NAME "
             "selects an entry of project.maneuvers by name; a bare flag "
             "runs the first entry. Writes the time-history CSV and the "
             "transient HTML report into the outputs folder.")
    maneuver_group.add_argument(
        "--maneuver-file", metavar="PATH", default=None,
        help="Run a maneuver defined in a .bemt file OUTSIDE the project "
             "(a saved ManeuverDefinition list).")
    maneuver_group.add_argument(
        "--list-maneuvers", action="store_true",
        help="Print the saved maneuver names of --project.")
    maneuver_group.add_argument(
        "--maneuver-dt", type=float, default=None, metavar="FLOAT",
        help="Override the sample interval dt_s for this run.")
    maneuver_group.add_argument(
        "--maneuver-substeps", type=int, default=None, metavar="INT",
        help="Override substeps_per_step for this run.")
    # NOTE: --rpm already exists below (ad hoc condition speed). --compare
    # reuses it when the project has no saved cases; see _run_compare.

    # --- Stability derivatives (SC-14) -----------------------------------
    derivative_group = p.add_argument_group("Stability derivatives (SC-14)")
    derivative_group.add_argument(
        "--derivatives", nargs="?", const="", default=None, metavar="NAME",
        help="Run a saved stability-derivative study. NAME selects an entry "
             "of project.derivatives; a bare flag runs the first one.")
    derivative_group.add_argument(
        "--list-derivatives", action="store_true",
        help="Print the saved derivative-study names of --project.")
    derivative_group.add_argument(
        "--derivatives-csv", metavar="PATH", default=None,
        help="Write the derivative matrix to this CSV instead of the "
             "default path under the project's outputs folder.")

    # --- ad hoc condition (used only if no --from-bemt-* is given and the
    # project has no batch.conditions) ----------------------------------
    # Phase 8 (docs/CHANGELOG.md): the representations of one component are
    # INTERCHANGEABLE representation pairs of the same physical quantity
    # (Section 6c of bemt.py). One flag per SLOT: the representations of the
    # in-plane component are mutually exclusive with each other, and so are
    # those of the along-shaft one. Parity with the GUI's unit dropdown
    # (RunCaseTab/RunBatchTab), which offers the same choice per row.
    p.add_argument("--rpm", type=float, default=None, help="RPM for ad hoc condition.")
    # NAMED BY SLOT, NOT BY LETTER. The flags and `--project` are parsed in
    # the same pass, so a flag cannot know the project's mode, but the
    # letter does: the in-plane component is mu_x on a rotor and mu_z on a
    # propeller. `--mu-inplane` is the in-plane component in both, and which
    # letter it is shown under is left to the surfaces that know the mode
    # (GUI, results table, report, `.bemt`). See `zbemt/nomenclature.py`.
    inplane_group = p.add_mutually_exclusive_group()
    inplane_group.add_argument("--mu-inplane", dest="mu_inplane", type=float, default=None,
                               help="IN-PLANE advance ratio (default 0.0, hover): "
                                    "V_inplane/(Omega*R). The component in the plane of "
                                    "the disk: a rotor's forward-flight advance, or a "
                                    "propeller's CROSS-flow (zero in straight cruise). "
                                    "Alternative to --j-inplane/--v-inplane.")
    inplane_group.add_argument("--j-inplane", dest="J_inplane", type=float, default=None,
                               help="IN-PLANE advance ratio in propeller form: "
                                    "V_inplane/(n*D) = pi*mu_inplane. NOT a propeller's "
                                    "own advance ratio. That one is along the shaft, "
                                    "--j-axial. Alternative to --mu-inplane.")
    inplane_group.add_argument("--v-inplane", dest="V_inplane", type=float, default=None,
                               help="IN-PLANE velocity [m/s]. Requires --rpm (the ratio "
                                    "is V/(Omega*R), and Omega comes from the RPM). "
                                    "Alternative to --mu-inplane.")
    inplane_group.add_argument("--alpha-disk-deg", dest="alpha_disk_deg", type=float, default=None,
                             help="Angle [deg] between the free stream and the SHAFT "
                                  "(0 = straight axial cruise, the propeller convention). "
                                  "The IN-PLANE component is derived from it and from the "
                                  "along-shaft one (--v-axial/--j-axial/--mu-axial), which "
                                  "is therefore required. "
                                  "Complement of --alpha-rotor-deg; the two are mutually "
                                  "exclusive because neither would set the velocity scale.")
    axial_group = p.add_mutually_exclusive_group()
    axial_group.add_argument("--v-axial", dest="V_axial", type=float, default=None,
                             help="ALONG-SHAFT velocity [m/s] (default 0.0): a rotor's "
                                  "climb (+) or descent (-), a propeller's AIRSPEED. "
                                  "Alternative to "
                                  "--j-axial/--mu-axial/--alpha-rotor-deg.")
    axial_group.add_argument("--j-axial", dest="J_axial", type=float, default=None,
                             help="ALONG-SHAFT advance ratio in propeller form: "
                                  "V_axial/(n*D). On a propeller this is THE J of the "
                                  "propeller charts, the one propulsive efficiency uses. "
                                  "Requires --rpm. Alternative to --v-axial.")
    axial_group.add_argument("--mu-axial", dest="mu_axial", type=float, default=None,
                             help="ALONG-SHAFT advance ratio in rotor form: "
                                  "V_axial/(Omega*R) = J_axial/pi. The same number as the "
                                  "free-stream inflow ratio lambda. Requires --rpm. "
                                  "Alternative to --v-axial.")
    axial_group.add_argument("--alpha-rotor-deg",
                              dest="alpha_rotor_deg", type=float, default=None,
                              help="Disk angle of attack [deg]. The ALONG-SHAFT "
                                   "component is derived from the in-plane one, --rpm "
                                   "(required with this flag) and the project's rotor "
                                   "radius. Measured from the disk PLANE and POSITIVE "
                                   "when the stream arrives from BELOW the disk, as an "
                                   "angle of attack is for a wing: a positive angle "
                                   "therefore gives a NEGATIVE along-shaft component, "
                                   "which opposes the induced velocity and raises the "
                                   "thrust. -90 deg is purely axial with the stream from "
                                   "above (climb). For the propeller convention, measured "
                                   "from the shaft and zero in straight cruise, use "
                                   "--alpha-disk-deg. Alternative to --v-axial. "
                                   "Rotor mode only; a propeller reads --alpha-disk-deg. "
                                   "(--disk-alpha-deg is kept as an alias of this flag.)")
    # The THIRD component (SC-15). The disk plane holds two directions, and
    # the in-plane group above names only one of them. This group names the
    # other, so the free stream can arrive from the side. Named by slot for
    # the same reason as the in-plane one: the letter y is lateral in both
    # modes, but the flag stays parallel to its two siblings.
    lateral_group = p.add_mutually_exclusive_group()
    lateral_group.add_argument("--v-lateral", dest="V_lateral", type=float, default=None,
                               help="LATERAL velocity [m/s] (default 0.0): the "
                                    "component sideways and in the plane of the "
                                    "disk. Sideward flight, or flight with "
                                    "sideslip. Alternative to "
                                    "--mu-lateral/--j-lateral/--sideslip-deg.")
    lateral_group.add_argument("--mu-lateral", dest="mu_lateral", type=float, default=None,
                               help="LATERAL advance ratio: V_lateral/(Omega*R). "
                                    "Requires --rpm. Alternative to --v-lateral.")
    lateral_group.add_argument("--j-lateral", dest="J_lateral", type=float, default=None,
                               help="LATERAL advance ratio in propeller form: "
                                    "V_lateral/(n*D) = pi*mu_lateral. Requires "
                                    "--rpm. Alternative to --v-lateral.")
    lateral_group.add_argument("--sideslip-deg", dest="sideslip_deg", type=float, default=None,
                               help="Sideslip angle [deg] of the in-plane free "
                                    "stream, atan2(V_lateral, V_inplane). It "
                                    "SPLITS the in-plane component into a lateral "
                                    "one and never sets the scale of a velocity, "
                                    "so it stays inside -89 to 89. For pure "
                                    "sideward flight use --v-lateral. Alternative "
                                    "to --v-lateral.")
    p.add_argument("--collective", type=float, default=8.0, help="Collective pitch [deg] for ad hoc.")
    p.add_argument("--cyclic", dest="cyclic", nargs=2, type=float, default=None,
                   metavar=("C", "S"),
                   help="Cyclic pitch for the ad hoc condition: the cosine and "
                        "sine 1/rev harmonics (theta_1c theta_1s), both in "
                        "degrees. It reaches the engine through the blade-motion "
                        "path, so it takes effect on a rigid blade only as an "
                        "azimuthal pitch; with flap freedom (SC-11) it is one "
                        "of the cyclic controls.")

    # --- Geometry (RotorGeometryDef) -- Part 3.3, geometry group ---------
    p.add_argument("--geom-preset", choices=["rectangular", "tapered", "elliptic", "custom"],
                    default=None, help="Generate project.geometry from a parametric preset.")
    p.add_argument("--geom-file", metavar="PATH", default=None,
                    help="Load entire project.geometry from a .bemt (RotorGeometryDef).")
    p.add_argument("--geom-radius", type=float, default=None,
                    help="Set the rotor radius, in metres (RotorGeometryDef.radius_m).")
    p.add_argument("--geom-root-cutout", type=float, default=None,
                    help="Set the root cutout, as a fraction of the radius "
                         "(RotorGeometryDef.root_cutout_norm).")
    p.add_argument("--geom-n-blades", type=int, default=None,
                    help="Set the number of blades (RotorGeometryDef.n_blades).")
    p.add_argument("--geom-chord", type=float, default=None,
                    help="constant chord_norm (rectangular preset).")
    p.add_argument("--geom-taper-ratio", type=float, default=None,
                    help="tip_chord_norm/root_chord_norm (tapered preset; requires --geom-chord "
                         "as root_chord_norm).")
    p.add_argument("--geom-max-chord", type=float, default=None,
                    help="max_chord_norm (elliptic preset).")
    p.add_argument("--geom-twist-root", type=float, default=None,
                    help="Set the generated twist at the root, in degrees "
                         "(linear twist preset).")
    p.add_argument("--geom-twist-tip", type=float, default=None,
                    help="Set the generated twist at the tip, in degrees "
                         "(linear twist preset).")
    p.add_argument("--geom-custom-points", metavar="r:c:t,r:c:t,...", default=None,
                    help="Point-by-point table (custom preset): r/R:chord_norm:twist_deg, "
                         "separated by comma.")

    # --- Blade dynamics (RotorGeometryDef.dynamics) -- SC-11 -------------
    p.add_argument("--flap-model", choices=["rigid", "offset", "spring", "offset_spring"],
                   default=None,
                   help="Choose the blade's flap freedom "
                        "(RotorGeometryDef.dynamics.flap_model): a rigid disk, a "
                        "hinge offset, a root spring, or both together.")
    p.add_argument("--hinge-offset", type=float, default=None,
                   help="Flap hinge offset e, as a fraction of the radius "
                        "(dynamics.hinge_offset_norm), 0 to 0.3.")
    p.add_argument("--lock-number", type=float, default=None,
                   help="Lock number gamma of the blade "
                        "(dynamics.lock_number); sets the aerodynamic-to-"
                        "inertial response ratio when the inertia source is "
                        "the Lock number.")

    # --- Airfoil (AirfoilDef) -- Part 3.3 -------------------------------
    p.add_argument("--airfoil-source", choices=["analytical", "table"], default=None,
                    help="Choose where the polar comes from (AirfoilDef.source).")
    p.add_argument("--airfoil-table", metavar="CSV", default=None,
                    help="Import a polar table (CSV) to AirfoilDef.table_slices "
                         "and set source='table' (same importer as airfoils.import_polar_csv).")
    p.add_argument("--dynamic-stall", dest="dynamic_stall", action="store_true", default=None,
                    help="Turn dynamic stall on (AirfoilDef.use_dynamic_stall=True).")
    p.add_argument("--no-dynamic-stall", dest="dynamic_stall", action="store_false",
                    help="Turn dynamic stall off (AirfoilDef.use_dynamic_stall=False).")
    # There is no flag for BEMTConfig.dynamic_stall_model: today only one
    # model is supported ("oye"), so the field has no real choice to
    # expose in the CLI. What turns dynamic stall on/off is the boolean
    # --dynamic-stall/--no-dynamic-stall above. The field still exists
    # in BEMTConfig (serialized, used by the GUI). If a second model is
    # implemented, this is where the choice flag should be added back.
    p.add_argument("--airfoil-stall-model", choices=["linear", "clip", "enhanced", "viterna"],
                    default=None,
                    help="Choose the shape of the STATIC polar beyond stall "
                         "(AirfoilDef.stall_model). 'linear' keeps rising. 'clip' and "
                         "'enhanced' plateau. 'viterna' extends to the full range, "
                         "+/-180 deg.")
    p.add_argument("--airfoil-sections-file", metavar="PATH", default=None,
                    help="Load project.airfoil_sections (multi-section) from a .bemt "
                         "(list of AirfoilDef).")

    # --- Config/Solver (BEMTConfig, stored in project.config) ------------
    p.add_argument("--inflow", default=None,
                    choices=["glauert_local", "glauert_global", "coleman_local", "coleman_global",
                             "drees_local", "drees_global", "pitt_peters_steady", "pitt_peters_unsteady"],
                    help="Choose the inflow field model (BEMTConfig.inflow_field_model).")
    p.add_argument("--prandtl-loss-mode", choices=["off", "tip", "root", "both"], default=None,
                    help="Choose which Prandtl tip and root losses apply (BEMTConfig.prandtl_loss_mode).")
    p.add_argument("--pitt-peters-outer-iter", type=int, default=None,
                    help="Set the outer iteration limit for Pitt-Peters (BEMTConfig.pitt_peters_outer_iter).")
    p.add_argument("--pitt-peters-relax", type=float, default=None,
                    help="Set the relaxation factor for Pitt-Peters (BEMTConfig.pitt_peters_relax).")
    p.add_argument("--pitt-peters-tol", type=float, default=None,
                    help="Set the convergence tolerance for Pitt-Peters (BEMTConfig.pitt_peters_tol).")
    p.add_argument("--rotational-augmentation", dest="rot_aug", action="store_true", default=None,
                    help="Turn rotational augmentation on, also called the Himmelskamp effect or the Snel correction (BEMTConfig.use_rotational_augmentation=True).")
    p.add_argument("--no-rotational-augmentation", dest="rot_aug", action="store_false",
                    help="Turn rotational augmentation off (BEMTConfig.use_rotational_augmentation=False).")
    p.add_argument("--radial-flow-correction", dest="radial_flow", action="store_true", default=None,
                    help="Turn the radial flow correction on (BEMTConfig.use_radial_flow_correction=True).")
    p.add_argument("--no-radial-flow-correction", dest="radial_flow", action="store_false",
                    help="Turn the radial flow correction off (BEMTConfig.use_radial_flow_correction=False).")
    p.add_argument("--solver", choices=["fixed_point", "newton", "bisection", "aitken"], default=None,
                    help="Choose the iterative solver (BEMTConfig.solver).")
    p.add_argument("--max-iter", type=int, default=None,
                    help="Set the iteration limit for the solver (BEMTConfig.max_iter).")
    p.add_argument("--tol", type=float, default=None,
                    help="Set the convergence tolerance for the solver (BEMTConfig.tol).")
    p.add_argument("--relax", type=float, default=None,
                    help="Set the relaxation factor for the solver (BEMTConfig.relax).")
    p.add_argument("--relax-schedule", dest="relax_schedule", action="store_true", default=None,
                    help="Turn the relaxation schedule on (BEMTConfig.relax_schedule=True).")
    p.add_argument("--no-relax-schedule", dest="relax_schedule", action="store_false",
                    help="Turn the relaxation schedule off (BEMTConfig.relax_schedule=False).")

    # --- Export ---------------------------------------------------------
    p.add_argument("--outdir", default=None,
                    help="Output folder. Default: <project>/batch.outdir if defined, "
                         "otherwise <project>/outputs.")
    p.add_argument("--plots", nargs="*", default=None,
                    help="Which plots to export (for example: performance disk_map). Default: "
                         "batch.plots from the selected batch, or the project's. "
                         "'--plots' without values = no plots.")
    p.add_argument("--no-csv", action="store_true", help="Do not write results.csv.")
    p.add_argument("--report", nargs="?", const="", default=None, metavar="FILE",
                    help="Generate a self-contained HTML report (summary table, mesh, "
                         "solver and rotor used, embedded plots). Without value, "
                         "write <outdir>/report.html. Same report as the "
                         "'Generate report...' button in the GUI.")
    p.add_argument("--report-notes", default=None, metavar="TEXT",
                    help="Notes text to embed in the report (--report).")
    p.add_argument("--export-layout", choices=["flat", "per_case"], default="flat",
                    help="Organization of PER-CONDITION plots (docs/plano_v3.md Part 4.3). "
                         "'flat' (default) = one file per case, self-explanatory name. "
                         "'per_case' = one folder per case.")

    # --- generic setter (S3, docs/production-plan.md) --------------------
    # Only 14/40 BEMTConfig fields and 3/25 AirfoilDef fields had a
    # dedicated flag. Creating about 50 new flags would make --help unreadable
    # and become a list that is easy to let drift. --set closes the gap
    # without that: any BEMTConfig/AirfoilDef/RotorGeometryDef field
    # becomes reachable, validated against the dataclass's real fields
    # (dataclasses.fields) and converted from its type annotation
    # (int/float/bool/str).
    p.add_argument(
        "--set", dest="set", action="append", default=[],
        metavar="NAMESPACE.FIELD=VALUE",
        help="Set any field of BEMTConfig/AirfoilDef/RotorGeometryDef directly, "
             "without needing a dedicated flag. NAMESPACE is 'config' (BEMTConfig, for example "
             "config.Ne=90, config.Npsi=144, config.rho=1.2, config.is_propeller=true), "
             "'airfoil' (AirfoilDef, for example airfoil.cd0=0.012) or 'geom' (RotorGeometryDef, "
             "for example geom.n_blades=3). Bool accepts true/false/1/0/yes/no. Repeatable "
             "(--set a=1 --set b=2). PRECEDENCE: --set is applied AFTER all dedicated "
             "flags above (--inflow, --geom-radius, --dynamic-stall, and so on), so in "
             "case of conflict --set always wins. Non-existent field name or value that does "
             "not convert to the field type is an error (SystemExit), never silently applied.")

    trim_group = p.add_argument_group("Trimmed run (fixed thrust/CT, bisection loop)")
    trim_group.add_argument(
        "--trim-mode", choices=["solve_rpm", "solve_collective"], default=None,
        help="Instead of running the condition as entered, solve for one DOF by bisection until "
             "a thrust or CT target is hit. 'solve_rpm' keeps --collective fixed and solves for RPM. "
             "'solve_collective' keeps --rpm fixed and solves for collective. Requires at least one "
             "condition to run (ad hoc, a saved case, or a batch) and exactly one of "
             "--trim-target-thrust/--trim-target-ct. For a batch, every queued "
             "condition is trimmed independently.")
    trim_target_group = trim_group.add_mutually_exclusive_group()
    trim_target_group.add_argument("--trim-target-thrust", type=float, default=None,
                                    help="Target Thrust [N] for --trim-mode.")
    trim_target_group.add_argument("--trim-target-ct", type=float, default=None,
                                    help="Target CT [-] for --trim-mode.")

    p.add_argument("--validate-only", action="store_true",
                    help="Only validate the project and flight condition, do not run the engine. "
                         "Useful before launching a long batch without supervision.")
    p.add_argument("--ignore-validation-errors", action="store_true",
                    help="Run even with validation errors (default is to abort). "
                         "Warnings never block.")

    return p


def _preprocess_argv(argv=None) -> list[str]:
    """Normalizes `argv` before parsing: `--alpha-range VAL` becomes
    `--alpha-range=VAL` so argparse is not confused when VAL starts
    with `-` (for example negative ranges, "-10:20:0.5")."""
    if argv is None:
        argv = sys.argv[1:]
    else:
        argv = list(argv)

    new_argv = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--alpha-range" and i + 1 < len(argv):
            new_argv.append(f"--alpha-range={argv[i+1]}")
            i += 2
        else:
            new_argv.append(arg)
            i += 1
    return new_argv


def _parse_args(argv=None) -> argparse.Namespace:
    return _build_parser().parse_args(_preprocess_argv(argv))


def _build_run_options_dataclass(parser: argparse.ArgumentParser):
    """Derives a dataclass with one field per parser flag (same `dest`,
    same default), so that `RunOptions` can never diverge from the
    argparse's real flags."""
    fields = []
    seen = set()
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        dest = action.dest
        if dest == argparse.SUPPRESS or dest in seen:
            continue
        seen.add(dest)
        default = action.default
        # dataclasses rejects a mutable default (list/dict/set) directly,
        # for example `--set` (action="append", default=[]). default_factory
        # captures the value by copy so instances don't share the same list.
        if isinstance(default, (list, dict, set)):
            fields.append((dest, typing.Any,
                            dataclasses.field(default_factory=lambda d=default: type(d)(d))))
        else:
            fields.append((dest, typing.Any, dataclasses.field(default=default)))
    return dataclasses.make_dataclass("RunOptions", fields)


RunOptions = _build_run_options_dataclass(_build_parser())


def _run_options_from_argv(cls, argv=None):
    ns = _parse_args(argv)
    return cls(**{f.name: getattr(ns, f.name) for f in dataclasses.fields(cls)})


RunOptions.from_argv = classmethod(_run_options_from_argv)


# =============================================================================
# Applying flags to the Project (Geometry/Airfoil/Config-Solver group,
# Part 3.3, item 3: setting via command line any field that today is only
# editable from the GUI)
# =============================================================================

def _apply_geometry_flags(project, args) -> None:
    g = project.geometry

    # `--geom-file` used to sit in an `elif` AFTER all the presets, so
    # `--geom-preset X --geom-file Y` used the preset and silently
    # discarded the file. There is no obvious answer for which should win, so
    # the right move is to reject the combination rather than pick one on our own.
    if args.geom_preset and args.geom_file:
        raise SystemExit(
            "cli.py: --geom-preset and --geom-file are mutually exclusive "
            "(both define the entire geometry). Choose one.")

    if args.geom_preset == "rectangular":
        project.geometry = geometry.generate_rectangular(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            chord_norm=args.geom_chord if args.geom_chord is not None else 0.08,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 12.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 4.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "tapered":
        root_chord = args.geom_chord if args.geom_chord is not None else 0.10
        tip_chord = root_chord * args.geom_taper_ratio if args.geom_taper_ratio is not None else 0.04
        project.geometry = geometry.generate_tapered(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            root_chord_norm=root_chord, tip_chord_norm=tip_chord,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 14.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 2.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "elliptic":
        project.geometry = geometry.generate_elliptic(
            root_cutout_norm=args.geom_root_cutout if args.geom_root_cutout is not None else g.root_cutout_norm,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            max_chord_norm=args.geom_max_chord if args.geom_max_chord is not None else 0.10,
            twist_root_deg=args.geom_twist_root if args.geom_twist_root is not None else 14.0,
            twist_tip_deg=args.geom_twist_tip if args.geom_twist_tip is not None else 2.0,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_preset == "custom":
        if not args.geom_custom_points:
            raise SystemExit("--geom-preset custom requires --geom-custom-points r:c:t,...")
        r_norm, chord_norm, twist_deg = [], [], []
        for point in args.geom_custom_points.split(","):
            r, c, t = point.split(":")
            r_norm.append(float(r)); chord_norm.append(float(c)); twist_deg.append(float(t))
        project.geometry = geometry.generate_custom(
            r_norm, chord_norm, twist_deg,
            radius_m=args.geom_radius if args.geom_radius is not None else g.radius_m,
            n_blades=args.geom_n_blades if args.geom_n_blades is not None else g.n_blades,
            airfoil_name=g.airfoil_name,
        )
    elif args.geom_file:
        from .models import load_bemt
        project.geometry = load_bemt(RotorGeometryDef, args.geom_file)
    else:
        # no preset/file: only overrides loose scalar fields, if given
        if args.geom_radius is not None:
            g.radius_m = args.geom_radius
        if args.geom_root_cutout is not None:
            g.root_cutout_norm = args.geom_root_cutout
        if args.geom_n_blades is not None:
            g.n_blades = args.geom_n_blades

    # --- blade dynamics (SC-11): the three fields a user changes most ----
    d = project.geometry.dynamics
    if args.flap_model is not None:
        d.flap_model = args.flap_model
    if args.hinge_offset is not None:
        d.hinge_offset_norm = args.hinge_offset
    if args.lock_number is not None:
        d.lock_number = args.lock_number


def _apply_airfoil_flags(project, args) -> None:
    a = project.airfoil
    if args.airfoil_source is not None:
        a.source = args.airfoil_source
    if args.airfoil_table:
        a.table_slices = airfoils.import_polar_csv(args.airfoil_table)
        a.source = "table"
    if args.dynamic_stall is not None:
        a.use_dynamic_stall = args.dynamic_stall
    if args.airfoil_stall_model is not None:
        a.stall_model = args.airfoil_stall_model
    if args.airfoil_sections_file:
        from .models import load_bemt_list
        project.airfoil_sections = load_bemt_list(AirfoilDef, args.airfoil_sections_file)


def _apply_config_flags(project, args) -> None:
    cfg = project.config   # dict (asdict de BEMTConfig)
    simple_map = {
        "inflow": "inflow_field_model",
        "prandtl_loss_mode": "prandtl_loss_mode",
        "pitt_peters_outer_iter": "pitt_peters_outer_iter",
        "pitt_peters_relax": "pitt_peters_relax",
        "pitt_peters_tol": "pitt_peters_tol",
        "solver": "solver",
        "max_iter": "max_iter",
        "tol": "tol",
        "relax": "relax",
    }
    for arg_name, cfg_key in simple_map.items():
        val = getattr(args, arg_name)
        if val is not None:
            cfg[cfg_key] = val
    if args.rot_aug is not None:
        cfg["use_rotational_augmentation"] = args.rot_aug
    if args.radial_flow is not None:
        cfg["use_radial_flow_correction"] = args.radial_flow
    if args.relax_schedule is not None:
        cfg["relax_schedule"] = args.relax_schedule


# =============================================================================
# generic --set (S3, docs/production-plan.md): closes the parity gap
# without creating about 50 new dedicated flags. See --set's help in _build_parser.
# =============================================================================

# namespace -> (attribute on Project, dataclass used to validate field/type)
_SET_NAMESPACE_DATACLASS = {
    "config": BEMTConfig,
    "airfoil": AirfoilDef,
    "geom": RotorGeometryDef,
}

_TRUE_STRINGS = {"true", "1", "yes"}
_FALSE_STRINGS = {"false", "0", "no"}


def _unwrap_optional(py_type):
    """`Optional[X]` (== `Union[X, None]`) -> X; any other type, unchanged."""
    if typing.get_origin(py_type) is typing.Union:
        args = [a for a in typing.get_args(py_type) if a is not type(None)]
        if len(args) == 1:
            return args[0]
    return py_type


def _convert_set_value(raw_value: str, py_type, field_name: str):
    py_type = _unwrap_optional(py_type)
    if py_type is bool:
        low = raw_value.strip().lower()
        if low in _TRUE_STRINGS:
            return True
        if low in _FALSE_STRINGS:
            return False
        raise ValueError(
            f"invalid boolean value {raw_value!r} for '{field_name}' "
            f"(use true/false/1/0/yes/no).")
    if py_type is int:
        try:
            return int(raw_value)
        except ValueError:
            raise ValueError(f"invalid integer value {raw_value!r} for '{field_name}'.")
    if py_type is float:
        try:
            return float(raw_value)
        except ValueError:
            raise ValueError(f"invalid numeric value {raw_value!r} for '{field_name}'.")
    if py_type is str:
        return raw_value
    raise ValueError(
        f"field '{field_name}' has type {py_type!r}, not supported by --set "
        f"(lists/dicts are not convertible from a string; use --geom-file/"
        f"--airfoil-sections-file/--airfoil-table for such fields).")


def _apply_set_flags(project, args) -> None:
    """Applies all --set flags, AFTER the dedicated flags (precedence
    documented in --help): in case of conflict, --set wins.

    The key walks NESTED dataclasses: ``geom.dynamics.flap_model=offset``
    descends ``project.geometry.dynamics`` field by field. This keeps a
    new nested block (SC-11 and friends) reachable from the CLI without a
    dedicated flag per field (PA-1/PA-3). ``config`` stays a flat
    namespace: it is a dict of BEMTConfig entries."""
    if not args.set:
        return

    type_hints_cache: dict = {}

    def _hints(cls):
        if cls not in type_hints_cache:
            type_hints_cache[cls] = typing.get_type_hints(cls)
        return type_hints_cache[cls]

    for item in args.set:
        if "=" not in item:
            raise SystemExit(
                f"--set: invalid format {item!r}, expected NAMESPACE.FIELD=VALUE "
                f"(for example --set config.Ne=90).")
        key, raw_value = item.split("=", 1)
        if "." not in key:
            raise SystemExit(
                f"--set: {key!r} needs a namespace (config./airfoil./geom.), "
                f"for example --set config.{key}=...")
        ns, path = key.split(".", 1)
        if ns not in _SET_NAMESPACE_DATACLASS:
            raise SystemExit(
                f"--set: invalid namespace {ns!r}. Valid: "
                f"{', '.join(sorted(_SET_NAMESPACE_DATACLASS))}.")
        steps = path.split(".")

        if ns == "config":
            # Flat namespace: one level over a BEMTConfig-shaped dict.
            if len(steps) != 1:
                raise SystemExit(
                    f"--set config.{path}: the config namespace does not "
                    "descend into sub-objects.")
            field_name = steps[0]
            valid_fields = {f.name for f in dataclasses.fields(BEMTConfig)}
            if field_name not in valid_fields:
                raise SystemExit(
                    f"--set: field 'config.{field_name}' does not exist in "
                    f"BEMTConfig. Valid fields: "
                    f"{', '.join(sorted(valid_fields))}.")
            try:
                value = _convert_set_value(
                    raw_value, _hints(BEMTConfig)[field_name], field_name)
            except ValueError as exc:
                raise SystemExit(f"--set: {exc}")
            project.config[field_name] = value
            continue

        owner = {"airfoil": project.airfoil, "geom": project.geometry}.get(ns)
        current = owner
        current_type = _SET_NAMESPACE_DATACLASS[ns]
        for depth, field_name in enumerate(steps):
            last = depth == len(steps) - 1
            valid_fields = {f.name for f in dataclasses.fields(current_type)}
            where = ".".join((ns,) + tuple(steps[:depth + 1]))
            if field_name not in valid_fields:
                raise SystemExit(
                    f"--set: field '{where}' does not exist in "
                    f"{current_type.__name__}. Valid fields: "
                    f"{', '.join(sorted(valid_fields))}.")
            py_type = _unwrap_optional(_hints(current_type)[field_name])
            if not last:
                if not dataclasses.is_dataclass(py_type):
                    raise SystemExit(
                        f"--set: '{where}' is not a nested dataclass; "
                        "the path cannot descend further.")
                current = getattr(current, field_name)
                current_type = py_type
                continue
            try:
                value = _convert_set_value(raw_value, py_type, field_name)
            except ValueError as exc:
                raise SystemExit(f"--set: {exc}")
            setattr(current, field_name, value)


# =============================================================================
# External polar engines (--gen-neuralfoil / --gen-xfoil), CLI mode
# =============================================================================

#: Engine -> flag that selects it, and engine -> name shown to the user.
#: A new external polar engine needs one entry in each dict, its
#: ``--gen-<engine>`` flag in the parser, and nothing else in this file.
_GEN_POLAR_FLAGS = {"neuralfoil": "--gen-neuralfoil", "xfoil": "--gen-xfoil"}
_GEN_POLAR_NAMES = {"neuralfoil": "NeuralFoil", "xfoil": "XFOIL"}


def _parse_float_list(text: str, flag: str) -> list[float]:
    try:
        return [float(v) for v in text.split(",") if v.strip()]
    except ValueError as exc:
        raise ValueError(f"Invalid value in {flag}={text!r}: {exc}") from exc


def _run_gen_polar(project, project_path, args, engine: str) -> int:
    """Shared handler for every --gen-* polar flag: only ``engine``
    differs between them (same required flags, same export/apply
    behavior). The three XFOIL transition options are the one exception:
    they exist for --gen-xfoil only."""
    flag = _GEN_POLAR_FLAGS[engine]
    if engine != "xfoil" and any(
            value is not None
            for value in (args.ncrit, args.xtr_top, args.xtr_bot)):
        print("Error: --ncrit/--xtr-top/--xtr-bot apply to --gen-xfoil.",
              file=sys.stderr)
        return 2
    if not args.airfoil_geometry:
        print(f"Error: {flag} requires --airfoil-geometry "
              "(a NACA 4-digit or 5-digit code, or a preset).",
              file=sys.stderr)
        return 2
    if not args.reynolds or not args.mach:
        print(f"Error: {flag} requires --reynolds and --mach (at least one value each).",
              file=sys.stderr)
        return 2

    try:
        geom = airfoils.resolve_geometry_spec(args.airfoil_geometry)
        reynolds_list = _parse_float_list(args.reynolds, "--reynolds")
        mach_list = _parse_float_list(args.mach, "--mach")
        lo_s, hi_s, step_s = args.alpha_range.split(":")
    except ValueError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    # Defaults come from the library; each option is forwarded only when
    # given on the command line.
    xfoil_kwargs = {}
    if engine == "xfoil":
        if args.ncrit is not None:
            xfoil_kwargs["ncrit"] = args.ncrit
        if args.xtr_top is not None:
            xfoil_kwargs["xtr_top"] = args.xtr_top
        if args.xtr_bot is not None:
            xfoil_kwargs["xtr_bot"] = args.xtr_bot

    diagnostics: list = []
    try:
        slices = api.run_external_polar_from_geometry(
            geom, engine=engine,
            reynolds_list=reynolds_list, mach_list=mach_list,
            alpha_min_deg=float(lo_s), alpha_max_deg=float(hi_s), alpha_step_deg=float(step_s),
            diagnostics=diagnostics,
            **xfoil_kwargs,
        )
    except (RuntimeError, ValueError) as exc:
        # Clear message (not a raw traceback). It covers the common case of
        # the engine's package or executable not being available here.
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    # Partial results (a Reynolds that produced no points, dropped alpha
    # points) must never pass silently on the command line either.
    for line in diagnostics:
        print(f"Warning: {line}", file=sys.stderr)

    print(f"{_GEN_POLAR_NAMES[engine]}: {len(slices)} polar tables generated "
          f"for {args.airfoil_geometry!r} "
          f"({len(reynolds_list)} Reynolds x {len(mach_list)} Mach).")

    if args.export_table:
        out = api.export_polar_table(slices, args.export_table)
        print(f"Table exported to {out}")
    else:
        project.airfoil.table_slices.extend(slices)
        project.airfoil.source = "table"
        api.save_project(project)
        print(f"Applied to project.airfoil.table_slices and saved to {project_path}.")
    return 0


# =============================================================================
# Design tools (--compare / --optimize): geometry comparison and design
# optimization, CLI mode
# =============================================================================

def _run_compare(project, args) -> int:
    """--compare: run this project's saved conditions over several blade
    geometries and always write comparison.csv/comparison.html into the
    outputs folder."""
    variants = {}
    for raw_path in str(args.compare).split(","):
        folder = raw_path.strip()
        if not folder:
            continue
        if not Path(folder).exists():
            # Plain interpolation, not {folder!r}: repr would double the
            # path separators on Windows and the printed path would no
            # longer match what the user typed.
            print(f"Error: --compare: project folder does not exist: {folder}",
                  file=sys.stderr)
            return 2
        try:
            other = api.open_project(folder)
        except (OSError, ValueError) as exc:
            print(f"Error: --compare: could not open {folder!r}: {exc}",
                  file=sys.stderr)
            return 1
        # The label is the project NAME stored in the folder's meta file,
        # which may differ from the folder name.
        variants[other.name] = other.geometry
    variants["base"] = project.geometry

    # No saved cases: run one default hover-like case at the RPM given
    # with --rpm. The engine has no defensible rpm default, so without
    # the flag the command stops with a clear instruction instead of a
    # deep traceback.
    conditions = list(project.saved_cases)
    if not conditions:
        rpm_value = getattr(args, "rpm", None)
        if not rpm_value:
            print("Error: --compare: this project has no saved cases and "
                  "--rpm was not given. Save a case in Run Case or pass "
                  "--rpm R to compare at that rotational speed.",
                  file=sys.stderr)
            return 2
        conditions = [FlightCondition(name="comparison",
                                      collective_deg=8.0,
                                      rpm=float(rpm_value))]
    try:
        results = api.compare_geometries(project, variants, conditions,
                                          trim=args.trim)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    outputs_dir = Path(api.project_outputs_dir(project, create=True))
    try:
        report = api.generate_comparison_report(
            results, str(outputs_dir / "comparison.html"), project=project,
            title=f"Geometry comparison - {project.name}")
        csv_path = api.export_comparison_csv(results,
                                              str(outputs_dir / "comparison.csv"))
    except (RuntimeError, ValueError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    # One line per variant at the FIRST condition it ran (results are
    # variant-major, so the first result carrying a label holds that
    # condition): CT for the load side and FM for hover quality are the
    # two numbers a planform comparison turns on first.
    first_by_label: dict = {}
    for res in results:
        first_by_label.setdefault(str(res.summary.get("geometry_label", "")), res)
    for label, res in first_by_label.items():
        parts = []
        if "CT" in res.summary:
            parts.append(f"CT={res.summary['CT']:.5g}")
        if "FM" in res.summary:
            parts.append(f"FM={res.summary['FM']:.5g}")
        print(f"[{res.condition_name}] {label}: " + ", ".join(parts))
    print(f"Report: {report}")
    print(f"CSV: {csv_path}")
    return 0


def _run_optimize(project, args) -> int:
    """--optimize: run one saved study and write its report plus the
    history CSV that lands beside it."""
    try:
        definition = api.get_optimization(project, args.optimize or None)
    except KeyError as exc:
        # exc.args[0]: str(KeyError) would wrap the message in another
        # pair of quotes, which reads like shell noise.
        message = exc.args[0] if exc.args else str(exc)
        print(f"Error: {message}", file=sys.stderr)
        return 1

    if args.max_evals is not None:
        definition = dataclasses.replace(definition, max_evals=int(args.max_evals))

    try:
        outcome = api.optimize_design(project, definition)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    outputs_dir = Path(api.project_outputs_dir(project, create=True))
    # The report file follows the STUDY's own name, not the command-line
    # argument: a bare --optimize runs the first entry, whose name may be
    # anything, and two studies must never overwrite each other's report.
    slug = api.sanitize_filename(definition.name)
    try:
        report = api.generate_optimization_report(
            outcome, str(outputs_dir / f"{slug}_optimization.html"),
            project=project, definition=definition)
    except (RuntimeError, ValueError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if outcome.best_results is None:
        print(f"Error: no finite evaluation was recorded ({outcome.message}); "
              f"the report was written to {report}.", file=sys.stderr)
        return 1

    print(f"Optimization '{definition.name}' finished: {outcome.message}.")
    print(f"Best parameters: "
          + ", ".join(f"{param_name}={param_value}"
                      for param_name, param_value in outcome.best_params.items()))
    print(f"Best {outcome.objective_key} ({outcome.objective_kind}): "
          f"{outcome.best_value:.6g}")
    print(f"Report: {report}")
    print(f"History CSV: {Path(report).with_name(Path(report).stem + '_history.csv')}")
    return 0


def _effective_algorithm(definition, args) -> str:
    """The search this run uses: the flag wins over the study's stored
    algorithm, which falls back to its legacy method alias."""
    return (getattr(args, "algorithm", None)
            or definition.algorithm or definition.method)


def _is_pareto_run(definition, args) -> bool:
    """A study with two objectives must never silently degrade to a
    single-objective search, so the objectives count forces the Pareto
    path even when no algorithm says so."""
    return len(definition.objectives) >= 2 \
        or _effective_algorithm(definition, args) in ("nsga2", "de")


def _apply_search_overrides(definition, args):
    """--algorithm/--population/--generations/--seed/--workers win over
    the values stored in the study for this one run."""
    overrides = {}
    if args.algorithm is not None:
        overrides["algorithm"] = args.algorithm
    if args.population is not None:
        overrides["population"] = int(args.population)
    if args.generations is not None:
        overrides["generations"] = int(args.generations)
    if args.seed is not None:
        overrides["seed"] = int(args.seed)
    if args.workers is not None:
        overrides["parallel_workers"] = int(args.workers)
    return dataclasses.replace(definition, **overrides) if overrides \
        else definition


def _print_front_table(definition, outcome) -> None:
    """The front as plain text: one row per design, variables first,
    then the objectives."""
    keys = list(outcome.objective_keys)
    param_names = list(outcome.param_names)
    header = ["#"] + param_names + keys
    print("  " + "  ".join(header))
    for i, (params, values) in enumerate(zip(outcome.front_params,
                                              outcome.front_values)):
        cells = [str(i)]
        cells += [f"{params[n]:.6g}" if isinstance(params.get(n), float)
                  else str(params.get(n, "")) for n in param_names]
        cells += [f"{values[k]:.6g}"
                  if isinstance(values.get(k), float) else str(values.get(k, ""))
                  for k in keys]
        print("  " + "  ".join(cells))


def _optimize_multi(project, definition, args) -> int:
    """The Pareto branch of --optimize (SC-13): runs the evolutionary
    search and writes the report, the front CSV and the evaluations CSV."""
    try:
        outcome = api.optimize_design_multi(project, definition)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    outputs_dir = Path(api.project_outputs_dir(project, create=True))
    # Same rule as the single-objective path: file names follow the
    # STUDY's name, so two studies never overwrite each other.
    slug = api.sanitize_filename(definition.name)
    front_csv = (Path(args.pareto_csv) if args.pareto_csv
                 else outputs_dir / f"{slug}_pareto_front.csv")
    try:
        report = api.generate_optimization_report(
            outcome, str(outputs_dir / f"{slug}_pareto.html"),
            project=project, definition=definition)
        api.export_pareto_csv(outcome, str(front_csv))
    except (RuntimeError, ValueError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if not outcome.front_params:
        print(f"Error: no evaluation was recorded ({outcome.message}); "
              f"the report was written to {report}.", file=sys.stderr)
        return 1

    keys = list(outcome.objective_keys)
    print(f"Pareto optimization '{definition.name}' finished: "
          f"{outcome.message}.")
    print("Objectives: " + ", ".join(keys))
    print(f"Front members: {len(outcome.front_params)}")
    _print_front_table(definition, outcome)
    print(f"Report: {report}")
    print(f"Front CSV: {front_csv}")
    evaluations_csv = Path(report).with_name(
        Path(report).stem + "_evaluations.csv")
    if evaluations_csv.exists():
        print(f"Evaluations CSV: {evaluations_csv}")
    return 0


def _run_optimize(project, args) -> int:
    """--optimize: run one saved study and write its artifacts. The
    study itself picks the path: two objectives or an nsga2/de algorithm
    go to the Pareto search; everything else stays derivative-free."""
    try:
        definition = api.get_optimization(project, args.optimize or None)
    except KeyError as exc:
        # exc.args[0]: str(KeyError) would wrap the message in another
        # pair of quotes, which reads like shell noise.
        message = exc.args[0] if exc.args else str(exc)
        print(f"Error: {message}", file=sys.stderr)
        return 1

    if args.max_evals is not None:
        definition = dataclasses.replace(definition, max_evals=int(args.max_evals))
    definition = _apply_search_overrides(definition, args)

    if _is_pareto_run(definition, args):
        return _optimize_multi(project, definition, args)

    try:
        outcome = api.optimize_design(project, definition)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    outputs_dir = Path(api.project_outputs_dir(project, create=True))
    # The report file follows the STUDY's own name, not the command-line
    # argument: a bare --optimize runs the first entry, whose name may be
    # anything, and two studies must never overwrite each other's report.
    slug = api.sanitize_filename(definition.name)
    try:
        report = api.generate_optimization_report(
            outcome, str(outputs_dir / f"{slug}_optimization.html"),
            project=project, definition=definition)
    except (RuntimeError, ValueError, OSError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if outcome.best_results is None:
        print(f"Error: no finite evaluation was recorded ({outcome.message}); "
              f"the report was written to {report}.", file=sys.stderr)
        return 1

    print(f"Optimization '{definition.name}' finished: {outcome.message}.")
    print(f"Best parameters: "
          + ", ".join(f"{param_name}={param_value}"
                      for param_name, param_value in outcome.best_params.items()))
    print(f"Best {outcome.objective_key} ({outcome.objective_kind}): "
          f"{outcome.best_value:.6g}")
    print(f"Report: {report}")
    print(f"History CSV: {Path(report).with_name(Path(report).stem + '_history.csv')}")
    return 0


def _run_derivatives(project, args) -> int:
    """--derivatives: run one saved study and write its matrix.

    The study carries its own trim, its own steps and its own list of
    states, controls and outputs, so the flag needs nothing but a name.
    A study whose trim does not converge now raises rather than
    returning a point that is not a trim, and the message reaches the
    shell unchanged."""
    try:
        request = api.get_derivative_request(project, args.derivatives or None)
    except KeyError as exc:
        # exc.args[0]: str(KeyError) wraps the message in another pair of
        # quotes, which reads like shell noise (same as `_run_optimize`).
        message = exc.args[0] if exc.args else str(exc)
        print(f"Error: {message}", file=sys.stderr)
        return 1

    try:
        outcome = api.compute_derivatives(project, request)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if args.derivatives_csv:
        destination = Path(args.derivatives_csv)
    else:
        outputs_dir = Path(api.project_outputs_dir(project, create=True))
        slug = api.sanitize_filename(request.name)
        destination = outputs_dir / f"{slug}_derivatives.csv"
    try:
        written = api.export_derivatives_csv(outcome, str(destination))
    except OSError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"Derivative study: {request.name}")
    for (output, variable), value in sorted(outcome.matrix.items()):
        print(f"  d{output}/d{variable}\t{value:.6g}")
    print(f"Matrix written to {written}")
    return 0


def _run_maneuver(project, args) -> int:
    """--maneuver: march one saved trajectory (SC-12) and write the time
    history plus the transient report. A bare --maneuver runs the first
    saved entry; --maneuver-file takes a definition from a .bemt file
    outside the project; --maneuver-dt/--maneuver-substeps override the
    stored sampling for one run."""
    if args.maneuver_file:
        from .models import ManeuverDefinition, load_bemt_list
        maneuvers = load_bemt_list(ManeuverDefinition, args.maneuver_file)
        if not maneuvers:
            print(f"Error: {args.maneuver_file} stores no maneuver.",
                  file=sys.stderr)
            return 1
        definition = maneuvers[0]
        if args.maneuver:
            matches = [m for m in maneuvers if m.name == args.maneuver]
            if not matches:
                print(f"Error: no maneuver named {args.maneuver!r} in "
                      f"{args.maneuver_file}. Available: "
                      f"{[m.name for m in maneuvers]}.", file=sys.stderr)
                return 1
            definition = matches[0]
    else:
        try:
            definition = api.get_maneuver(project, args.maneuver or None)
        except ValueError as exc:
            print(f"Error: {exc}", file=sys.stderr)
            return 1

    if args.maneuver_dt is not None:
        definition = dataclasses.replace(definition,
                                          dt_s=float(args.maneuver_dt))
    if args.maneuver_substeps is not None:
        definition = dataclasses.replace(
            definition, substeps_per_step=int(args.maneuver_substeps))

    def _progress(done, total, row):
        if done % max(total // 10, 1) == 0 or done == total:
            print(f"  sample {done}/{total}  t={row['t']:.3f}s  "
                  f"CT={row['CT']:.5f}")

    try:
        history, _maps_list = api.run_maneuver(
            project, definition, on_sample_done=_progress)
    except (RuntimeError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    outputs_dir = Path(api.project_outputs_dir(project, create=True))
    slug = api.sanitize_filename(definition.name)
    csv_path = outputs_dir / f"{slug}_maneuver.csv"
    api.export_maneuver_csv(history, str(csv_path))

    from zbemt.models import Results as _Results
    results = [_Results(summary=row.to_dict(), maps=mp,
                         condition_name=f"t={row['t']:.3f}s")
               for (_, row), mp in zip(history.iterrows(), _maps_list)]
    report = None
    if not getattr(args, "no_report_maneuver", False):
        try:
            report = api.generate_report(
                results, str(outputs_dir / f"{slug}_maneuver.html"),
                project=project)
        except (RuntimeError, ValueError, OSError) as exc:
            print(f"Warning: report failed ({exc})", file=sys.stderr)

    settled = ""
    if {"nu0", "CT"} <= set(history.columns) and len(history) >= 2:
        first = history.iloc[0]
        settled = (f" | inflow nu0 from {first['nu0']:.4f} "
                   f"to {history.iloc[-1]['nu0']:.4f}")
    print(f"Maneuver '{definition.name}' marched {len(history)} samples"
          f"{settled}.")
    print(f"Time-history CSV: {csv_path}")
    if report:
        print(f"Report: {report}")
    return 0


# =============================================================================
# main
# =============================================================================

def main(argv=None, options=None) -> int:
    # If called with no arguments (argv=None and sys.argv empty), inject a default.
    # This allows running as "python zbemt/cli.py" and getting useful behavior
    # without breaking usage with explicit argv or RunOptions.
    if argv is None and options is None and len(sys.argv) == 1:
        argv = ["--project", DEFAULT_PROJECT_PATH,
                "--rpm", str(DEFAULT_RPM), "--validate-only"]

    args = options if options is not None else RunOptions.from_argv(argv)

    if args.new:
        project = api.new_project(args.new, name=args.name)
        project_path = args.new
    else:
        try:
            project = api.open_project(args.project)
        except (ValueError, OSError) as exc:
            # A project that cannot be read is the user's file being
            # wrong, not the program failing. A traceback buries the one
            # line that says which condition is at fault.
            print(f"cli.py: error: cannot open {args.project!r}: {exc}",
                  file=sys.stderr)
            return 2
        project_path = args.project

    if args.list_batches:
        # A sweep batch stores `sweep_params`, not a list of conditions.
        # Printing `len(conditions)` said "0 condition(s)" for all of
        # them, which sounded like an empty batch. What matters here is
        # how many cases the sweep WILL generate.
        for b in project.batches:
            if b.conditions:
                count_text = f"{len(b.conditions)} explicit condition(s)"
            else:
                params = b.sweep_params or {}
                if b.sweep_kind == "factorial":
                    # Factorial: the product of the axes, not the number of axes.
                    axes = [axis.get("values", []) for axis in params.get("axes", [])]
                else:
                    axes = [v for v in params.values() if isinstance(v, (list, tuple))]
                n = 1
                for axis in axes:
                    n *= max(len(axis), 1)
                count_text = (f"{n} sweep case(s)" if axes
                              else "no conditions defined")
            print(f"{b.name}\t{count_text}\tsweep_kind={b.sweep_kind}")
        return 0
    if args.list_cases:
        for c in project.saved_cases:
            print(f"{c.name}\tmu={c.mu_x}\tcollective_deg={c.collective_deg}\tVv={c.Vz}\trpm={c.rpm}")
        return 0
    if args.list_derivatives:
        studies = getattr(project, "derivatives", [])
        if not studies:
            print("This project stores no derivative studies "
                  "(inputs/derivatives.bemt absent or empty).")
        for d in studies:
            variables = ", ".join([*d.states, *d.controls]) or "(none)"
            print(f"{d.name}\ttrim={d.trim}\tvariables: {variables}")
        return 0
    if args.list_maneuvers:
        maneuvers = getattr(project, "maneuvers", [])
        if not maneuvers:
            print("This project stores no maneuvers "
                  "(inputs/maneuvers.bemt absent or empty).")
        for m in maneuvers:
            times = ", ".join(f"{p.t_s:g}s" for p in m.points[:4])
            more = " ..." if len(m.points) > 4 else ""
            print(f"{m.name}\t{len(m.points)} point(s)\tt: {times}{more}\t"
                  f"dt={m.dt_s:g}s")
        return 0

    # The design-tool modes are alternative jobs, not modifiers: each one
    # runs its own workflow and writes its own artifacts, so two of them
    # in one call has no defined meaning. argparse cannot express this
    # conflict (the polar flags and the design flags live in different
    # argument groups), so the check is explicit. It sits before any flag
    # application because it is a pure command-line conflict.
    selected_modes = [flag for flag, given in (
        ("--compare", bool(args.compare)),
        ("--optimize", args.optimize is not None),
        ("--gen-neuralfoil", bool(args.gen_neuralfoil)),
        ("--gen-xfoil", bool(args.gen_xfoil)),
        ("--maneuver", args.maneuver is not None),
        ("--derivatives", args.derivatives is not None),
    ) if given]
    if len(selected_modes) > 1:
        print("cli.py: error: " + ", ".join(selected_modes)
              + " are mutually exclusive. Give at most one of "
              "--compare, --optimize, --gen-neuralfoil, --gen-xfoil, "
              "--maneuver or --derivatives.",
              file=sys.stderr)
        return 2

    if args.gen_neuralfoil:
        return _run_gen_polar(project, project_path, args, "neuralfoil")
    if args.gen_xfoil:
        return _run_gen_polar(project, project_path, args, "xfoil")
    if args.compare:
        return _run_compare(project, args)
    if args.optimize is not None:
        return _run_optimize(project, args)
    if args.maneuver is not None:
        return _run_maneuver(project, args)
    if args.derivatives is not None:
        return _run_derivatives(project, args)

    _apply_geometry_flags(project, args)
    _apply_airfoil_flags(project, args)
    _apply_config_flags(project, args)
    _apply_set_flags(project, args)   # AFTER the dedicated ones: --set wins on conflict

    if args.save_as:
        project.path = args.save_as
        api.save_project(project)
        project_path = args.save_as

    # --- resolve what to run: saved batch > saved case > existing
    # batch.conditions > ad hoc condition (parity Part 3.3, item 1-2) -----
    # The two angles are in different exclusive GROUPS (the axis one is
    # the in-plane component, and the disk one is the axial), so `argparse`
    # cannot express "one from each group, except this combination".
    # Without the explicit check, `--alpha-disk-deg 6 --alpha-rotor-deg 84`
    # used to pass and resolve Vz from a still-zero mu_x: Vz=0, a silent
    # hover condition instead of the requested cruise.
    if args.alpha_disk_deg is not None and args.alpha_rotor_deg is not None:
        print("cli.py: error: --alpha-disk-deg and --alpha-rotor-deg are the "
              "same angle written two ways (alpha_disk = 90 - alpha_rotor): with "
              "both, neither velocity component sets the scale. Give one angle "
              "plus a dimensional or non-dimensional component "
              "(--vz/--jz/--muz for the axial one, --mux/--jx for the in-plane).",
              file=sys.stderr)
        return 2

    if args.from_bemt_batch:
        batch = api.get_batch(project, args.from_bemt_batch)
    elif args.from_bemt_case:
        case = api.get_saved_case(project, args.from_bemt_case)
        batch = BatchDefinition(name=f"cli_case_{case.name}", conditions=[case])
    else:
        radius_m = project.geometry.radius_m

        def _axial(mu_known: float):
            """Axial component [m/s]. Only the disk-angle branch depends
            on the already-resolved in-plane component."""
            if args.alpha_rotor_deg is not None:
                if args.rpm is None:
                    return None, ("cli.py: error: --alpha-rotor-deg requires --rpm "
                                  "(the axial component is derived from the in-plane "
                                  "one, the rpm and the rotor radius).")
                return api.vv_from_alpha_deg(args.alpha_rotor_deg, mu_known,
                                              args.rpm, radius_m), None
            if args.J_axial is not None or args.mu_axial is not None:
                if args.rpm is None:
                    return None, ("cli.py: error: --j-axial/--mu-axial require --rpm "
                                  "(the axial speed is mu*Omega*R, and Omega comes "
                                  "from the RPM).")
                mu = (api.J_to_mu(args.J_axial) if args.J_axial is not None
                      else args.mu_axial)
                return api.mu_to_V(mu, args.rpm, radius_m), None
            if args.V_axial is not None:
                return args.V_axial, None
            return 0.0, None

        # ORDER: normally the in-plane component is the known one and the
        # axial one can be derived from it (--alpha-rotor-deg). With
        # --alpha-disk-deg the dependency inverts, because the in-plane comes out
        # of the axial, so the axial comes first. Same inversion as
        # `bemt.resolve_advance_velocity`.
        if args.alpha_disk_deg is not None:
            if args.rpm is None:
                print("cli.py: error: --alpha-disk-deg requires --rpm "
                      "(the in-plane component is tan(alpha_disk)*Vz, and mu_x needs Omega*R).",
                      file=sys.stderr)
                return 2
            Vz, error_message = _axial(0.0)
            if error_message:
                print(error_message, file=sys.stderr)
                return 2
            # |Vz|: same reason as `bemt.resolve_advance_velocity`.
            mu_x = api.V_to_mu(
                float(np.tan(np.deg2rad(args.alpha_disk_deg))) * abs(Vz),
                args.rpm, radius_m)
        else:
            if args.mu_inplane is not None:
                mu_x = args.mu_inplane
            elif args.J_inplane is not None:
                mu_x = api.J_to_mu(args.J_inplane)
            elif args.V_inplane is not None:
                if args.rpm is None:
                    print("cli.py: error: --v-inplane requires --rpm (the ratio is "
                          "V/(Omega*R), and Omega comes from the RPM).", file=sys.stderr)
                    return 2
                mu_x = api.V_to_mu(args.V_inplane, args.rpm, radius_m)
            else:
                mu_x = 0.0   # default: hover
            Vz, error_message = _axial(mu_x)
            if error_message:
                print(error_message, file=sys.stderr)
                return 2

        # The lateral component (SC-15). The angle spelling travels as the
        # angle, exactly as a saved case carries it; the three velocity
        # spellings become `Vy`. Only one of the two ever leaves here
        # non-zero, which is the rule `validation` enforces.
        Vy, sideslip_deg = 0.0, 0.0
        if args.sideslip_deg is not None:
            sideslip_deg = float(args.sideslip_deg)
        elif args.V_lateral is not None:
            Vy = float(args.V_lateral)
        elif args.mu_lateral is not None or args.J_lateral is not None:
            if args.rpm is None:
                print("cli.py: error: --mu-lateral/--j-lateral require --rpm "
                      "(the ratio is V/(Omega*R), and Omega comes from the RPM).",
                      file=sys.stderr)
                return 2
            mu_y = (float(args.mu_lateral) if args.mu_lateral is not None
                    else api.J_to_mu(float(args.J_lateral)))
            Vy = api.mu_to_V(mu_y, args.rpm, radius_m)

        condition = FlightCondition(
            name="cli", rpm=args.rpm, mu_x=mu_x, Vz=Vz,
            Vy=Vy, sideslip_deg=sideslip_deg,
            collective_deg=args.collective,
            cyclic_c_deg=(args.cyclic[0] if args.cyclic else 0.0),
            cyclic_s_deg=(args.cyclic[1] if args.cyclic else 0.0),
        )
        batch = BatchDefinition(name="cli_adhoc", conditions=[condition])

    # Validation BEFORE running: without this, a configuration the solver
    # rejects (an unimplemented inflow model, an unknown airfoil source)
    # only failed deep inside, with a raw traceback, possibly
    # after hours of unsupervised batch. `api.validate_project` already
    # existed exactly for this and the CLI never called it.
    issues = api.validate_project(project, conditions=batch.conditions)
    errors = [i for i in issues if i.level == "error"]
    if issues:
        stream = sys.stderr if errors else sys.stdout
        print("Project validation:", file=stream)
        for issue in issues:
            print(f"  {issue}", file=stream)
    if errors and not args.ignore_validation_errors:
        print(f"\ncli.py: {len(errors)} validation error(s). Nothing was run.\n"
              f"Use --ignore-validation-errors to run anyway.", file=sys.stderr)
        return 2

    if args.validate_only:
        print("\n--validate-only: project verified, nothing was run.")
        return 0

    if args.trim_mode is not None:
        if args.trim_target_thrust is None and args.trim_target_ct is None:
            print("cli.py: error: --trim-mode requires --trim-target-thrust or --trim-target-ct.",
                  file=sys.stderr)
            return 2
        target_kind = "thrust" if args.trim_target_thrust is not None else "CT"
        target_value = args.trim_target_thrust if args.trim_target_thrust is not None else args.trim_target_ct
        try:
            results = api.run_batch(project, batch, trim_mode=args.trim_mode,
                                    target_kind=target_kind, target_value=target_value)
        except ValueError as exc:
            print(f"cli.py: error: {exc}", file=sys.stderr)
            return 2
    else:
        results = api.run_batch(project, batch)

    # `batch` here may be a NAMED batch (--from-bemt-batch) or the ad hoc
    # one built above, either of which may carry its own outdir/plots.
    outdir = args.outdir or batch.outdir or str(Path(project_path) / "outputs")
    # `--plots` with no values (nargs="*") becomes [], which is not None
    # and therefore SUPPRESSED the project's plots instead of falling back
    # to the default. An explicit empty list now means "no plots", and the
    # flag's absence still means "use what the project asked for".
    if args.plots is None:
        plots = batch.plots or None
    else:
        plots = args.plots or None

    written = api.export_results(results, outdir=outdir, plots=plots,
                                  save_csv=not args.no_csv, project=project,
                                  layout=args.export_layout)

    # The report uses the plots that apply to the selection (default of
    # `api.generate_report`), regardless of `--plots`: `--plots` controls
    # what ends up on disk as standalone PNGs, `--report` controls what
    # gets embedded in the HTML. Passing an empty `--plots` to save files
    # should not empty out the report.
    if args.report is not None:
        report_path = args.report or str(Path(outdir) / "report.html")
        written.append(str(api.generate_report(
            results, report_path, project=project,
            title=f"zBEMT Report: {project.name}",
            notes=args.report_notes)))

    # Both coefficient families are always in `summary` (see
    # `bemt.aggregate_results`). What changes is which one the user wants
    # to read. Printing FM for a propeller is worse than useless: FM is the
    # figure of merit for HOVER, and an aircraft propeller never hovers.
    # The number comes out low and looks like a bad design, when the
    # metric simply does not apply. The one that fills this role on the
    # propeller side is `eta_prop`.
    is_propeller = bool(project.config.get("is_propeller"))
    if is_propeller:
        coeff_keys = ("J_z", "CT_prop", "CQ_prop", "CP_prop", "eta_prop")
    else:
        coeff_keys = ("CT", "CQ", "CP", "FM")

    for res in results:
        summary = res.summary
        keys = [k for k in coeff_keys if k in summary]
        # The key is the ENGINE's. What gets printed is the letter this mode
        # shows: a propeller's along-shaft advance ratio is J_x on screen,
        # in the report and in its `.bemt` file, so printing the internal
        # `J_z` here would make the CLI the one surface that disagrees.
        parts = ", ".join(
            f"{nomenclature.display_key(k, is_propeller)}={summary[k]:.5g}"
            for k in keys)
        print(f"[{res.condition_name}] {parts}")

    if written:
        print("Files generated:")
        for w in written:
            print(f"  {w}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
