"""Documentation-anchor resolution: which section of documentation.html
explains a given field, with no Qt dependency.

Split out of `field_help.py` so that reading the documentation and mapping
fields to it works on a machine with no PyQt6 installed. `help_registry.py`
uses this module for the plain-text tooltip, and the CLI-side
documentation tests use it too. `field_help.py` re-exports every name here
for the widgets that DO need Qt (the clickable popup itself); this module
is the one to import when only the mapping is needed.

See `field_help.py`'s module docstring for the anchor-resolution rules.
"""
from __future__ import annotations

import re
from functools import lru_cache
from typing import NamedTuple

#: `"any.field" — description`: the field name in the widget's tooltip
_NAME_IN_TOOLTIP = re.compile(r'^\s*"([\w.]+)"')

#: id="ajuda-{field}" in the HTML documentation — last resort
_HELP_ID = re.compile(r'id="ajuda-([\w.]+)"')

#: loose `<a id="x"></a>` (the HTML anchors physics sections this way) or
#: `<hN ...>` heading (with or without its own id).
_TOKEN = re.compile(r'<a id="([\w.\-]+)"\s*>\s*</a>|<h([1-6])([^>]*)>')
_ID_ATTR = re.compile(r'id="([\w.\-]+)"')

#: blocks generated by `tools/field_index.py` — cite EVERY field of the tab
_FIELD_INDEX_BLOCK = re.compile(
    r"<!--\s*INDICE-DE-CAMPOS:.*?/INDICE-DE-CAMPOS:[\w-]+\s*-->", re.DOTALL)

#: `<span class="bemt">.bemt</span>` — marks the section that DECLARES the
#: field (the authoritative one), distinguishing it from any other that only cites it.
_BEMT_MARK = 'class="bemt"'
_GUI_MARK = 'class="gui"'

#: Sections that cite a field WITHOUT being its section, as
#: ``(field, anchor)`` pairs excluded from `_best_section`.
#:
#: The map is keyed on the bare name, so any section that prints
#: ``<code>field</code>`` competes with the field's own section --
#: including lists that merely name it among others. §8.8.4 ("Export
#: without committing the project to disk") lists ``r_norm`` among the
#: columns of the exported CSV; its body is shorter than the radial
#: station's own §8.1.3, so the tie-break handed the help link to the
#: export section. Extend this table only when another bare name gains
#: a citation that is a list, never an explanation.
_NOT_THE_FIELDS_SECTION = frozenset({
    ("r_norm", "cap-3-8-3"),
    #: The Design Optimization chapter lists the variable parameters it
    #: may turn; every one of them is a Geometry-tab field documented in
    #: its own section there, never in the optimizer chapter.
    *{(name, "cap-opt-variables") for name in (
        "root_chord_norm", "tip_chord_norm", "twist_root_deg",
        "twist_tip_deg", "max_chord_norm", "chord_norm", "n_blades",
        "radius_m", "root_cutout_norm")},
    #: Section 15.2 lists the keys ONE TRAJECTORY POINT carries. Every
    #: one of them is a Run Case field with a section of its own, and
    #: that section is where the help belongs: the transient chapter
    #: names them, it does not explain them.
    *{(name, "cap-transiente-2") for name in (
        "mu_x", "Vz", "collective_deg", "cyclic_c_deg", "cyclic_s_deg",
        "rpm")},
    #: The interfaces chapter is an OVERVIEW. Its "Where the files go"
    #: paragraph names the two keys a batch carries so the reader knows
    #: they exist; the Run Batch chapter is where they are explained,
    #: and that is where the control has to land.
    ("outdir", "cap-interfaces-5-2"),
    ("plots", "cap-interfaces-5-2"),
})

#: chapters whose subject is physics/math, not widget description
_PHYSICS_CHAPTERS = frozenset({
    "physics-fundamentals",   # 2. Physics fundamentals
    "hover",                  # 3. Hover
    "forward-flight",         # 4. Forward flight
    "inflow-models",          # 7. Inflow models
    "physical-corrections",   # 8. Physical corrections
    "numerical-solver",       # 9. Numerical solver
})


class Section(NamedTuple):
    """A documentation section, with its body up to the next heading."""
    anchor: str
    level: int
    chapter: str
    body: str
    #: equivalent anchors (the HTML marks several before the same
    #: heading, for example `cap-24` and `s16` for 8.4). Internal links use either.
    aliases: tuple = ()

    @property
    def describes_widget(self) -> bool:
        """Field-description section (has the GUI/.bemt/CLI marks).

        This is what separates "9.3.1 Mesh and general physics" (a
        widget table) from "2.3 …" (the derivation): the two live in
        the same chapter, so the chapter alone does not distinguish them.
        """
        return _BEMT_MARK in self.body or _GUI_MARK in self.body

    @property
    def eh_fisica(self) -> bool:
        return self.chapter in _PHYSICS_CHAPTERS and not self.describes_widget


def _documentation_html() -> str:
    from .. import paths
    path = paths.documentation_path()
    if path is None:
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


@lru_cache(maxsize=1)
def documentation_sections() -> tuple[Section, ...]:
    """All sections of the HTML, in order, with body and source chapter.

    A heading with no ``id`` of its own inherits the immediately
    preceding loose ``<a id="...">`` anchor, which is how the document
    marks physics sections.
    """
    html = _FIELD_INDEX_BLOCK.sub("", _documentation_html())
    if not html:
        return ()

    sections: list[Section] = []
    pending: list[str] = []
    current: tuple | None = None   # (anchor, level, chapter, aliases)
    body_start = 0
    chapter = ""

    for tok in _TOKEN.finditer(html):
        loose_anchor, level_text, attrs = tok.group(1), tok.group(2), tok.group(3)
        if loose_anchor is not None:
            pending.append(loose_anchor)
            continue

        # closes the previous section at the start of this heading
        if current is not None:
            sections.append(Section(current[0], current[1], current[2],
                                html[body_start:tok.start()], current[3]))

        level = int(level_text)
        own_match = _ID_ATTR.search(attrs or "")
        aliases = tuple(pending)
        if own_match:
            anchor = own_match.group(1)
            aliases += (anchor,)
        elif pending:
            # prefers the "cap-*" anchor when there is a pair (cap-N + sN)
            caps = [a for a in pending if a.startswith("cap-")]
            anchor = caps[0] if caps else pending[-1]
        else:
            anchor = ""
        pending.clear()

        if level <= 2:
            chapter = anchor
        current = (anchor, level, chapter, aliases)
        body_start = tok.end()

    if current is not None:
        sections.append(Section(current[0], current[1], current[2],
                            html[body_start:], current[3]))

    return tuple(s for s in sections
                 if s.anchor and not s.anchor.startswith("ajuda-"))


def _cites_field(section: Section, field: str) -> bool:
    """Does the section mention ``<code>field</code>`` (with or without a prefix)?"""
    pattern = re.compile(r"<code>(?:[\w]+\.)?" + re.escape(field) + r"</code>")
    return bool(pattern.search(section.body))


#: "…derivation in <a href="#X">" / "Complete physics in <a href="#X">":
#: the document itself says where each GUI block's physics lives.
_DERIVATION_LINK = re.compile(
    r'(?:derivation|derivations|physics)[^<]{0,80}<a href="#([\w.\-]+)"',
    re.IGNORECASE)
_ANY_LINK = re.compile(r'<a href="#([\w.\-]+)"')


@lru_cache(maxsize=1)
def _physics_anchors() -> frozenset:
    """Anchors (and their aliases) that lead to a physics section."""
    out: set[str] = set()
    for s in documentation_sections():
        if s.eh_fisica:
            out.add(s.anchor)
            out.update(s.aliases)
    return frozenset(out)


def _ancestors(index: int) -> list:
    """Sections that contain the one at index ``index``, closest first up to the root."""
    sections = documentation_sections()
    level = sections[index].level
    out = []
    for i in range(index - 1, -1, -1):
        if sections[i].level < level:
            out.append(sections[i])
            level = sections[i].level
            if level <= 2:
                break
    return out


def _physics_jump(index: int) -> str | None:
    """Follows the section's (or its ancestors') "derivation in …" link
    to the corresponding physics chapter.

    This is what avoids maintaining a field->physics map by hand: the
    document already says, in each GUI block, where the full derivation is.
    """
    physics = _physics_anchors()
    sections = documentation_sections()
    own_section = sections[index]

    # 1. the text itself says "…derivation in <a href="#X">"
    matches = [a for a in _DERIVATION_LINK.findall(own_section.body) if a in physics]
    if matches:
        return matches[0]

    # 2. a single physics link in the body: no ambiguity to resolve
    unique_links = list(dict.fromkeys(
        a for a in _ANY_LINK.findall(own_section.body) if a in physics))
    if len(unique_links) == 1:
        return unique_links[0]

    # 3. the parent block declares where the set's derivation is
    for ancestor in _ancestors(index):
        matches = [a for a in _DERIVATION_LINK.findall(ancestor.body)
                   if a in physics]
        if matches:
            return matches[0]
    return None


def _best_section(field: str) -> str | None:
    """Section that explains ``field``: its own.

    The documentation is organized one chapter per GUI tab, and a field's
    section carries everything about it: the physics, the mathematics,
    the options and how to set it in all three interfaces. So the answer
    is simply the section that DECLARES the field (the one with the
    ``.bemt`` mark), and the help opens there.

    It used to jump onward to the physics chapter, because the per-field
    sections were thin and delegated the derivation elsewhere. Now that
    the derivations live with the fields, that jump would carry the
    reader AWAY from the explanation instead of toward it.
    """
    sections = documentation_sections()
    candidates = [s for s in sections if _cites_field(s, field)
                  and (field, s.anchor) not in _NOT_THE_FIELDS_SECTION]
    if not candidates:
        return None
    best = max(candidates,
                 key=lambda s: (_BEMT_MARK in s.body, s.level, -len(s.body)))
    return best.anchor


def _is_physics_section(anchor: str) -> bool:
    """Does the anchor point to a physics section (not table/widget)?"""
    return anchor in _physics_anchors()


@lru_cache(maxsize=1)
def _field_table_rows() -> dict[str, str]:
    """``{field: "ajuda-field"}`` — the last resort."""
    from ..bemt import BEMTConfig
    from ..models import AirfoilDef, FlightCondition, RotorGeometryDef

    known: set[str] = set()
    for cls in (BEMTConfig, AirfoilDef, RotorGeometryDef, FlightCondition):
        known |= set(cls.__dataclass_fields__)

    html = _documentation_html()
    return {name: f"ajuda-{name}"
            for name in _HELP_ID.findall(html) if name in known}


@lru_cache(maxsize=1)
def field_map() -> dict:
    """``{field_name: anchor}``, derived from the documentation itself.

    The anchor is the physics section that explains the field whenever
    one exists; the field-table row is only used for fields that no
    section cites (metadata like ``origin``, which has no physics).
    """
    table_rows = _field_table_rows()
    from . import help_content

    names = set(table_rows) | set(help_content.FIELD_HELP)
    mapping: dict[str, str] = {}
    for name in sorted(names):
        anchor = _best_section(name) or table_rows.get(name)
        if anchor:
            mapping[name] = anchor
    return mapping


def field_anchor(field: str) -> str | None:
    """Full-documentation HTML anchor for ``field``, or None."""
    name = field.split(".")[-1]
    anchor = field_map().get(name)
    if anchor:
        return anchor
    from . import help_content
    data = help_content.FIELD_HELP.get(name)
    return data.get("anchor") if data else None
