"""Documentation-anchor resolution: which section of documentation.html
explains a given field, with no Qt dependency.

Split out of `field_help.py` so that reading the documentation and mapping
fields to it -- used by `help_registry.py` for the plain-text tooltip, and
by the CLI-side documentation tests -- works on a machine with no PyQt6
installed. `field_help.py` re-exports every name here for the widgets that
DO need Qt (the clickable popup itself); this module is the one to import
when only the mapping is needed.

See `field_help.py`'s module docstring for the anchor-resolution rules.
"""
from __future__ import annotations

import re
from functools import lru_cache
from typing import NamedTuple

#: `"any.field" — description`: the field name in the widget's tooltip
_NOME_NO_TOOLTIP = re.compile(r'^\s*"([\w.]+)"')

#: id="ajuda-{field}" in the HTML documentation — last resort
_AJUDA_ID = re.compile(r'id="ajuda-([\w.]+)"')

#: loose `<a id="x"></a>` (the HTML anchors physics sections this way) or
#: `<hN ...>` heading (with or without its own id).
_TOKEN = re.compile(r'<a id="([\w.\-]+)"\s*>\s*</a>|<h([1-6])([^>]*)>')
_ID_ATTR = re.compile(r'id="([\w.\-]+)"')

#: blocks generated by `tools/field_index.py` — cite EVERY field of the tab
_INDICE_DE_CAMPOS = re.compile(
    r"<!--\s*INDICE-DE-CAMPOS:.*?/INDICE-DE-CAMPOS:[\w-]+\s*-->", re.DOTALL)

#: `<span class="bemt">.bemt</span>` — marks the section that DECLARES the
#: field (the authoritative one), distinguishing it from any other that only cites it.
_MARCA_BEMT = 'class="bemt"'
_MARCA_GUI = 'class="gui"'

#: chapters whose subject is physics/math, not widget description
_CAPITULOS_DE_FISICA = frozenset({
    "physics-fundamentals",   # 2. Physics fundamentals
    "hover",                  # 3. Hover
    "forward-flight",         # 4. Forward flight
    "inflow-models",          # 7. Inflow models
    "physical-corrections",   # 8. Physical corrections
    "numerical-solver",       # 9. Numerical solver
})


class Secao(NamedTuple):
    """A documentation section, with its body up to the next heading."""
    ancora: str
    nivel: int
    capitulo: str
    corpo: str
    #: equivalent anchors (the HTML marks several before the same
    #: heading, e.g. `cap-24` and `s16` for 8.4) — internal links use either.
    apelidos: tuple = ()

    @property
    def descreve_widget(self) -> bool:
        """Field-description section (has the GUI/.bemt/CLI marks).

        This is what separates "9.3.1 Mesh and general physics" (a
        widget table) from "2.3 …" (the derivation): the two live in
        the same chapter, so the chapter alone does not distinguish them.
        """
        return _MARCA_BEMT in self.corpo or _MARCA_GUI in self.corpo

    @property
    def eh_fisica(self) -> bool:
        return self.capitulo in _CAPITULOS_DE_FISICA and not self.descreve_widget


def _html_da_documentacao() -> str:
    from .. import paths
    caminho = paths.documentation_path()
    if caminho is None:
        return ""
    try:
        return caminho.read_text(encoding="utf-8")
    except OSError:
        return ""


@lru_cache(maxsize=1)
def secoes_da_documentacao() -> tuple[Secao, ...]:
    """All sections of the HTML, in order, with body and source chapter.

    A heading with no ``id`` of its own inherits the immediately
    preceding loose ``<a id="...">`` anchor — that is how the document
    marks physics sections.
    """
    html = _INDICE_DE_CAMPOS.sub("", _html_da_documentacao())
    if not html:
        return ()

    secoes: list[Secao] = []
    pendentes: list[str] = []
    atual: tuple | None = None   # (anchor, level, chapter, aliases)
    inicio_corpo = 0
    capitulo = ""

    for tok in _TOKEN.finditer(html):
        ancora_solta, nivel_txt, atributos = tok.group(1), tok.group(2), tok.group(3)
        if ancora_solta is not None:
            pendentes.append(ancora_solta)
            continue

        # closes the previous section at the start of this heading
        if atual is not None:
            secoes.append(Secao(atual[0], atual[1], atual[2],
                                html[inicio_corpo:tok.start()], atual[3]))

        nivel = int(nivel_txt)
        proprio = _ID_ATTR.search(atributos or "")
        apelidos = tuple(pendentes)
        if proprio:
            ancora = proprio.group(1)
            apelidos += (ancora,)
        elif pendentes:
            # prefers the "cap-*" anchor when there is a pair (cap-N + sN)
            caps = [a for a in pendentes if a.startswith("cap-")]
            ancora = caps[0] if caps else pendentes[-1]
        else:
            ancora = ""
        pendentes.clear()

        if nivel <= 2:
            capitulo = ancora
        atual = (ancora, nivel, capitulo, apelidos)
        inicio_corpo = tok.end()

    if atual is not None:
        secoes.append(Secao(atual[0], atual[1], atual[2],
                            html[inicio_corpo:], atual[3]))

    return tuple(s for s in secoes
                 if s.ancora and not s.ancora.startswith("ajuda-"))


def _cita(secao: Secao, campo: str) -> bool:
    """Does the section mention ``<code>field</code>`` (with or without a prefix)?"""
    padrao = re.compile(r"<code>(?:[\w]+\.)?" + re.escape(campo) + r"</code>")
    return bool(padrao.search(secao.corpo))


#: "…derivation in <a href="#X">" / "Complete physics in <a href="#X">":
#: the document itself says where each GUI block's physics lives.
_LINK_DE_DERIVACAO = re.compile(
    r'(?:derivation|derivations|physics)[^<]{0,80}<a href="#([\w.\-]+)"',
    re.IGNORECASE)
_QUALQUER_LINK = re.compile(r'<a href="#([\w.\-]+)"')


@lru_cache(maxsize=1)
def _ancoras_de_fisica() -> frozenset:
    """Anchors (and their aliases) that lead to a physics section."""
    saida: set[str] = set()
    for s in secoes_da_documentacao():
        if s.eh_fisica:
            saida.add(s.ancora)
            saida.update(s.apelidos)
    return frozenset(saida)


def _ancestrais(indice: int) -> list:
    """Sections that contain the one at index ``indice``, closest first up to the root."""
    secoes = secoes_da_documentacao()
    nivel = secoes[indice].nivel
    saida = []
    for i in range(indice - 1, -1, -1):
        if secoes[i].nivel < nivel:
            saida.append(secoes[i])
            nivel = secoes[i].nivel
            if nivel <= 2:
                break
    return saida


def _salto_para_fisica(indice: int) -> str | None:
    """Follows the section's (or its ancestors') "derivation in …" link
    to the corresponding physics chapter.

    This is what avoids maintaining a field->physics map by hand: the
    document already says, in each GUI block, where the full derivation is.
    """
    fisica = _ancoras_de_fisica()
    secoes = secoes_da_documentacao()
    propria = secoes[indice]

    # 1. the text itself says "…derivation in <a href="#X">"
    achados = [a for a in _LINK_DE_DERIVACAO.findall(propria.corpo) if a in fisica]
    if achados:
        return achados[0]

    # 2. a single physics link in the body: no ambiguity to resolve
    unicos = list(dict.fromkeys(
        a for a in _QUALQUER_LINK.findall(propria.corpo) if a in fisica))
    if len(unicos) == 1:
        return unicos[0]

    # 3. the parent block declares where the set's derivation is
    for ancestral in _ancestrais(indice):
        achados = [a for a in _LINK_DE_DERIVACAO.findall(ancestral.corpo)
                   if a in fisica]
        if achados:
            return achados[0]
    return None


def _melhor_secao(campo: str) -> str | None:
    """Section that explains ``field``: its own.

    The documentation is organised one chapter per GUI tab, and a field's
    section carries everything about it -- the physics, the mathematics,
    the options and how to set it in all three interfaces. So the answer
    is simply the section that DECLARES the field (the one with the
    ``.bemt`` mark), and the help opens there.

    It used to jump onward to the physics chapter, because the per-field
    sections were thin and delegated the derivation elsewhere. Now that
    the derivations live with the fields, that jump would carry the
    reader AWAY from the explanation instead of towards it.
    """
    secoes = secoes_da_documentacao()
    candidatas = [s for s in secoes if _cita(s, campo)]
    if not candidatas:
        return None
    melhor = max(candidatas,
                 key=lambda s: (_MARCA_BEMT in s.corpo, s.nivel, -len(s.corpo)))
    return melhor.ancora


def _e_secao_de_fisica(ancora: str) -> bool:
    """Does the anchor point to a physics section (not table/widget)?"""
    return ancora in _ancoras_de_fisica()


@lru_cache(maxsize=1)
def _linhas_da_tabela_de_campos() -> dict[str, str]:
    """``{field: "ajuda-field"}`` — the last resort."""
    from ..bemt import BEMTConfig
    from ..models import AirfoilDef, FlightCondition, RotorGeometryDef

    conhecidos: set[str] = set()
    for cls in (BEMTConfig, AirfoilDef, RotorGeometryDef, FlightCondition):
        conhecidos |= set(cls.__dataclass_fields__)

    html = _html_da_documentacao()
    return {nome: f"ajuda-{nome}"
            for nome in _AJUDA_ID.findall(html) if nome in conhecidos}


@lru_cache(maxsize=1)
def mapa_de_campos() -> dict:
    """``{field_name: anchor}``, derived from the documentation itself.

    The anchor is the physics section that explains the field whenever
    one exists; the field-table row is only used for fields that no
    section cites (metadata like ``origin``, which has no physics).
    """
    tabela = _linhas_da_tabela_de_campos()
    from . import help_content

    nomes = set(tabela) | set(help_content.FIELD_HELP)
    mapa: dict[str, str] = {}
    for nome in sorted(nomes):
        ancora = _melhor_secao(nome) or tabela.get(nome)
        if ancora:
            mapa[nome] = ancora
    return mapa


def ancora_do_campo(campo: str) -> str | None:
    """Full-documentation HTML anchor for ``field``, or None."""
    nome = campo.split(".")[-1]
    ancora = mapa_de_campos().get(nome)
    if ancora:
        return ancora
    from . import help_content
    dados = help_content.FIELD_HELP.get(nome)
    return dados.get("anchor") if dados else None


# Historical internal name, still used within this module.
_ancora_do_campo = ancora_do_campo
