"""Per-field contextual help: clickable labels and texts open the popup.

There is no more "?" button anywhere in the GUI (neither per field nor
per block): the field's own label is clickable, and on *spanning* rows
(whole-row checkboxes, which have no label) it is the checkbox's TEXT
that opens the popup — the box itself keeps toggling normally.

Fields with no entry in ``help_content.FIELD_HELP`` get a plain QLabel
(no clickable behavior) — a failure in the right direction: better no
interaction than an empty popup.

Anchor resolution (the destination of "Open full documentation →")
--------------------------------------------------------------
Each field's destination is DERIVED from ``docs/documentation.html``,
never kept by hand. The rule, in order of preference:

1. the deepest section of a PHYSICS chapter (2 Physics
   fundamentals, 7 Inflow models, 8 Physical corrections, 9 Numerical
   solver, 3 Hover, 4 Forward flight) that cites ``<code>field</code>``;
2. the deepest section of any other chapter that cites it (the
   per-tab sections, which at least describe the widget);
3. only then the ``id="ajuda-{field}"`` row of the field table.

Rule 3 used to be the FIRST one — and because of that every help link
fell into a table row cell instead of the physics. The field index
lists (``<!-- INDICE-DE-CAMPOS:... -->``) are removed before the
scan: they cite every field of the tab in ``<code>`` and would make any
chapter "cite" everything.
"""
from __future__ import annotations

import re
from functools import lru_cache
from typing import NamedTuple

from PyQt6.QtCore import QEvent, QObject, Qt
from PyQt6.QtWidgets import (
    QAbstractButton,
    QCheckBox,
    QFormLayout,
    QSizePolicy,
    QToolButton,
    QWidget,
)

#: `"any.field" — description`: the field name in the widget's tooltip
_NOME_NO_TOOLTIP = re.compile(r'^\s*"([\w.]+)"')

#: id="ajuda-{field}" in the HTML documentation — last resort
_AJUDA_ID = re.compile(r'id="ajuda-([\w.]+)"')

#: loose `<a id="x"></a>` (the HTML anchors physics sections this way) or
#: `<hN ...>` heading (with or without its own id).
_TOKEN = re.compile(r'<a id="([\w.\-]+)"\s*>\s*</a>|<h([1-6])([^>]*)>')
_ID_ATTR = re.compile(r'id="([\w.\-]+)"')

#: blocks generated by `tools/field_index.py` — cite EVERY field of the tab
_INDICE_DE_CAMPOS = re.compile(
    r"<!--\s*INDICE-DE-CAMPOS:.*?/INDICE-DE-CAMPOS:[\w-]+\s*-->", re.DOTALL)

#: `<span class="bemt">.bemt</span>` — marks the section that DECLARES the
#: field (the authoritative one), distinguishing it from any other that only cites it.
_MARCA_BEMT = 'class="bemt"'
_MARCA_GUI = 'class="gui"'

#: chapters whose subject is physics/math, not widget description
_CAPITULOS_DE_FISICA = frozenset({
    "physics-fundamentals",   # 2. Physics fundamentals
    "hover",                  # 3. Hover
    "forward-flight",         # 4. Forward flight
    "inflow-models",          # 7. Inflow models
    "physical-corrections",   # 8. Physical corrections
    "numerical-solver",       # 9. Numerical solver
})


class Secao(NamedTuple):
    """A documentation section, with its body up to the next heading."""
    ancora: str
    nivel: int
    capitulo: str
    corpo: str
    #: equivalent anchors (the HTML marks several before the same
    #: heading, e.g. `cap-24` and `s16` for 8.4) — internal links use either.
    apelidos: tuple = ()

    @property
    def descreve_widget(self) -> bool:
        """Field-description section (has the GUI/.bemt/CLI marks).

        This is what separates "9.3.1 Mesh and general physics" (a
        widget table) from "2.3 …" (the derivation): the two live in
        the same chapter, so the chapter alone does not distinguish them.
        """
        return _MARCA_BEMT in self.corpo or _MARCA_GUI in self.corpo

    @property
    def eh_fisica(self) -> bool:
        return self.capitulo in _CAPITULOS_DE_FISICA and not self.descreve_widget


def _html_da_documentacao() -> str:
    from .. import paths
    caminho = paths.documentation_path()
    if caminho is None:
        return ""
    try:
        return caminho.read_text(encoding="utf-8")
    except OSError:
        return ""


@lru_cache(maxsize=1)
def secoes_da_documentacao() -> tuple[Secao, ...]:
    """All sections of the HTML, in order, with body and source chapter.

    A heading with no ``id`` of its own inherits the immediately
    preceding loose ``<a id="...">`` anchor — that is how the document
    marks physics sections.
    """
    html = _INDICE_DE_CAMPOS.sub("", _html_da_documentacao())
    if not html:
        return ()

    secoes: list[Secao] = []
    pendentes: list[str] = []
    atual: tuple | None = None   # (anchor, level, chapter, aliases)
    inicio_corpo = 0
    capitulo = ""

    for tok in _TOKEN.finditer(html):
        ancora_solta, nivel_txt, atributos = tok.group(1), tok.group(2), tok.group(3)
        if ancora_solta is not None:
            pendentes.append(ancora_solta)
            continue

        # closes the previous section at the start of this heading
        if atual is not None:
            secoes.append(Secao(atual[0], atual[1], atual[2],
                                html[inicio_corpo:tok.start()], atual[3]))

        nivel = int(nivel_txt)
        proprio = _ID_ATTR.search(atributos or "")
        apelidos = tuple(pendentes)
        if proprio:
            ancora = proprio.group(1)
            apelidos += (ancora,)
        elif pendentes:
            # prefers the "cap-*" anchor when there is a pair (cap-N + sN)
            caps = [a for a in pendentes if a.startswith("cap-")]
            ancora = caps[0] if caps else pendentes[-1]
        else:
            ancora = ""
        pendentes.clear()

        if nivel <= 2:
            capitulo = ancora
        atual = (ancora, nivel, capitulo, apelidos)
        inicio_corpo = tok.end()

    if atual is not None:
        secoes.append(Secao(atual[0], atual[1], atual[2],
                            html[inicio_corpo:], atual[3]))

    return tuple(s for s in secoes
                 if s.ancora and not s.ancora.startswith("ajuda-"))


def _cita(secao: Secao, campo: str) -> bool:
    """Does the section mention ``<code>field</code>`` (with or without a prefix)?"""
    padrao = re.compile(r"<code>(?:[\w]+\.)?" + re.escape(campo) + r"</code>")
    return bool(padrao.search(secao.corpo))


#: "…derivation in <a href="#X">" / "Complete physics in <a href="#X">":
#: the document itself says where each GUI block's physics lives.
_LINK_DE_DERIVACAO = re.compile(
    r'(?:derivation|derivations|physics)[^<]{0,80}<a href="#([\w.\-]+)"',
    re.IGNORECASE)
_QUALQUER_LINK = re.compile(r'<a href="#([\w.\-]+)"')


@lru_cache(maxsize=1)
def _ancoras_de_fisica() -> frozenset:
    """Anchors (and their aliases) that lead to a physics section."""
    saida: set[str] = set()
    for s in secoes_da_documentacao():
        if s.eh_fisica:
            saida.add(s.ancora)
            saida.update(s.apelidos)
    return frozenset(saida)


def _ancestrais(indice: int) -> list:
    """Sections that contain the one at index ``indice``, closest first up to the root."""
    secoes = secoes_da_documentacao()
    nivel = secoes[indice].nivel
    saida = []
    for i in range(indice - 1, -1, -1):
        if secoes[i].nivel < nivel:
            saida.append(secoes[i])
            nivel = secoes[i].nivel
            if nivel <= 2:
                break
    return saida


def _salto_para_fisica(indice: int) -> str | None:
    """Follows the section's (or its ancestors') "derivation in …" link
    to the corresponding physics chapter.

    This is what avoids maintaining a field->physics map by hand: the
    document already says, in each GUI block, where the full derivation is.
    """
    fisica = _ancoras_de_fisica()
    secoes = secoes_da_documentacao()
    propria = secoes[indice]

    # 1. the text itself says "…derivation in <a href="#X">"
    achados = [a for a in _LINK_DE_DERIVACAO.findall(propria.corpo) if a in fisica]
    if achados:
        return achados[0]

    # 2. a single physics link in the body: no ambiguity to resolve
    unicos = list(dict.fromkeys(
        a for a in _QUALQUER_LINK.findall(propria.corpo) if a in fisica))
    if len(unicos) == 1:
        return unicos[0]

    # 3. the parent block declares where the set's derivation is
    for ancestral in _ancestrais(indice):
        achados = [a for a in _LINK_DE_DERIVACAO.findall(ancestral.corpo)
                   if a in fisica]
        if achados:
            return achados[0]
    return None


def _melhor_secao(campo: str) -> str | None:
    """Section that explains ``field``: its own.

    The documentation is organised one chapter per GUI tab, and a field's
    section carries everything about it -- the physics, the mathematics,
    the options and how to set it in all three interfaces. So the answer
    is simply the section that DECLARES the field (the one with the
    ``.bemt`` mark), and the help opens there.

    It used to jump onward to the physics chapter, because the per-field
    sections were thin and delegated the derivation elsewhere. Now that
    the derivations live with the fields, that jump would carry the
    reader AWAY from the explanation instead of towards it.
    """
    secoes = secoes_da_documentacao()
    candidatas = [s for s in secoes if _cita(s, campo)]
    if not candidatas:
        return None
    melhor = max(candidatas,
                 key=lambda s: (_MARCA_BEMT in s.corpo, s.nivel, -len(s.corpo)))
    return melhor.ancora


def _e_secao_de_fisica(ancora: str) -> bool:
    """Does the anchor point to a physics section (not table/widget)?"""
    return ancora in _ancoras_de_fisica()


@lru_cache(maxsize=1)
def _linhas_da_tabela_de_campos() -> dict[str, str]:
    """``{field: "ajuda-field"}`` — the last resort."""
    from ..bemt import BEMTConfig
    from ..models import AirfoilDef, FlightCondition, RotorGeometryDef

    conhecidos: set[str] = set()
    for cls in (BEMTConfig, AirfoilDef, RotorGeometryDef, FlightCondition):
        conhecidos |= set(cls.__dataclass_fields__)

    html = _html_da_documentacao()
    return {nome: f"ajuda-{nome}"
            for nome in _AJUDA_ID.findall(html) if nome in conhecidos}


@lru_cache(maxsize=1)
def mapa_de_campos() -> dict:
    """``{field_name: anchor}``, derived from the documentation itself.

    The anchor is the physics section that explains the field whenever
    one exists; the field-table row is only used for fields that no
    section cites (metadata like ``origin``, which has no physics).
    """
    tabela = _linhas_da_tabela_de_campos()
    from . import help_content

    nomes = set(tabela) | set(help_content.FIELD_HELP)
    mapa: dict[str, str] = {}
    for nome in sorted(nomes):
        ancora = _melhor_secao(nome) or tabela.get(nome)
        if ancora:
            mapa[nome] = ancora
    return mapa


def ancora_do_campo(campo: str) -> str | None:
    """Full-documentation HTML anchor for ``field``, or None."""
    nome = campo.split(".")[-1]
    ancora = mapa_de_campos().get(nome)
    if ancora:
        return ancora
    from . import help_content
    dados = help_content.FIELD_HELP.get(nome)
    return dados.get("anchor") if dados else None


# Historical internal name, still used within this module.
_ancora_do_campo = ancora_do_campo


def _campo_do_widget(widget: QWidget) -> str | None:
    """Raw field name (``"n_blades"``) extracted from the widget's tooltip."""
    achado = _NOME_NO_TOOLTIP.match(widget.toolTip() or "")
    return achado.group(1).split(".")[-1] if achado else None


def _abrir_popup(campo: str, perto_de: QWidget, raiz: QWidget) -> None:
    from .help_popup import HelpPopup
    from . import help_content
    from .common import open_help

    if campo in help_content.FIELD_HELP:
        HelpPopup.instancia(raiz).mostrar_campo(campo, perto_de)
    else:
        open_help(raiz, anchor=ancora_do_campo(campo))


def _label_clicavel(campo: str, texto_original: str, raiz: QWidget) -> QToolButton:
    """QToolButton that looks like a QLabel and opens the HelpPopup on click."""
    btn = QToolButton()
    btn.setText(texto_original)
    btn.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonTextOnly)
    btn.setAutoRaise(True)
    btn.setSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
    btn.setMinimumHeight(30)
    btn.setStyleSheet(
        "QToolButton { border: none; padding: 0; margin: 0;"
        " text-align: left; color: palette(windowText); }"
        "QToolButton:hover { color: #3a6dbd; text-decoration: underline; }"
    )
    btn.setCursor(Qt.CursorShape.PointingHandCursor)
    btn.setToolTip("Click the label for help on this field")

    btn.clicked.connect(lambda: _abrir_popup(campo, btn, raiz))
    return btn


class _CliqueNoTextoDoCheck(QObject):
    """Clicking a checkbox's TEXT opens help; clicking the BOX toggles it.

    Replaces the old "?" button on *spanning* rows: the widget is not
    wrapped in any container, so the form's layout (and what
    ``tools/field_index.py`` reads from it) stays exactly as it was.
    """

    def __init__(self, botao: QAbstractButton, campo: str, raiz: QWidget):
        super().__init__(botao)
        self._botao = botao
        self._campo = campo
        self._raiz = raiz
        botao.installEventFilter(self)

    def _largura_da_caixa(self) -> int:
        """End of the checkbox's mark region, in widget pixels."""
        from PyQt6.QtWidgets import QStyle
        estilo = self._botao.style()
        largura = estilo.pixelMetric(
            QStyle.PixelMetric.PM_IndicatorWidth, None, self._botao)
        espaco = estilo.pixelMetric(
            QStyle.PixelMetric.PM_CheckBoxLabelSpacing, None, self._botao)
        margem = estilo.pixelMetric(
            QStyle.PixelMetric.PM_FocusFrameHMargin, None, self._botao)
        return largura + espaco + 2 * max(margem, 1)

    def clique_e_no_texto(self, x: int) -> bool:
        return x > self._largura_da_caixa()

    def _sublinhar(self, ligado: bool) -> None:
        """Toggles the checkbox text's underline on/off.

        A regular field's label gets underlined on hover (that's what
        announces "this is clickable"); the checkbox had the click and
        the hand cursor, but no VISUAL cue -- and a cursor only appears
        after the mouse is already there. QSS does not solve it:
        `text-decoration` does not apply to `QCheckBox` text, which the
        style draws itself. Changing the widget's font works and does
        not depend on the stylesheet.
        """
        fonte = self._botao.font()
        if fonte.underline() != ligado:
            fonte.setUnderline(ligado)
            self._botao.setFont(fonte)

    def eventFilter(self, obj: QObject, evento: QEvent) -> bool:
        tipo = evento.type()
        if tipo == QEvent.Type.MouseButtonPress:
            try:
                x = int(evento.position().x())
            except AttributeError:                     # pragma: no cover
                return False
            if self.clique_e_no_texto(x):
                _abrir_popup(self._campo, self._botao, self._raiz)
                return True        # consume: the box does NOT toggle
        elif tipo in (QEvent.Type.HoverMove, QEvent.Type.HoverEnter):
            # Underlines only when the cursor is over the TEXT -- over the
            # box the click toggles, and underlining there would promise
            # help that click doesn't open.
            try:
                x = int(evento.position().x())
            except AttributeError:                     # pragma: no cover
                return False
            self._sublinhar(self.clique_e_no_texto(x))
        elif tipo == QEvent.Type.HoverLeave:
            self._sublinhar(False)
        return False


def _instalar_no_checkbox(widget: QWidget, campo: str, raiz: QWidget) -> bool:
    """Makes a checkbox's text clickable. Returns True if it installed."""
    if not isinstance(widget, QCheckBox):
        return False
    filtro = _CliqueNoTextoDoCheck(widget, campo, raiz)
    widget._filtro_de_ajuda = filtro
    widget.setCursor(Qt.CursorShape.PointingHandCursor)
    # Without `setAttribute(WA_Hover)` Qt only sends HoverMove to widgets
    # that already use hover in the style -- and the text underline would
    # never appear.
    widget.setAttribute(Qt.WidgetAttribute.WA_Hover, True)
    tooltip = widget.toolTip() or ""
    marca = "Click the text for help; click the box to toggle."
    if marca not in tooltip:
        widget.setToolTip(f"{tooltip}\n\n{marca}" if tooltip else marca)
    return True


def instalar_popups_de_campo(raiz: QWidget) -> int:
    """Makes the label (or checkbox text) of every documented field
    under ``raiz`` clickable. Returns how many fields were equipped.
    Idempotent: an already-equipped field does not get double treatment.
    """
    from . import help_content

    criados = 0
    for form in raiz.findChildren(QFormLayout):
        for linha in range(form.rowCount()):
            eh_spanning = form.itemAt(linha, QFormLayout.ItemRole.LabelRole) is None
            field_role = (QFormLayout.ItemRole.SpanningRole if eh_spanning
                          else QFormLayout.ItemRole.FieldRole)
            item_field = form.itemAt(linha, field_role)
            if item_field is None:
                continue
            widget = item_field.widget()
            if widget is None or getattr(widget, "_tem_popup_de_campo", False):
                continue

            campo = _campo_do_widget(widget)
            if campo is None:
                continue

            ancora = ancora_do_campo(campo)
            if ancora is None and campo not in help_content.FIELD_HELP:
                continue  # undocumented field — no interaction

            if eh_spanning:
                # No label: the checkbox's own text opens the help.
                if not _instalar_no_checkbox(widget, campo, raiz):
                    continue
            else:
                item_label = form.itemAt(linha, QFormLayout.ItemRole.LabelRole)
                label_widget = item_label.widget() if item_label else None
                if label_widget is None:
                    continue
                texto = label_widget.text() if hasattr(label_widget, "text") else campo
                # The row may already be HIDDEN by the tab's progressive
                # disclosure (`common.definir_linha_visivel`, called in
                # the constructor -- therefore before this point).
                # `QFormLayout` does not reapply the row's visibility to a
                # widget inserted later: the new label would be born
                # visible over a hidden field, which is exactly the
                # orphan label that `definir_linha_visivel` exists to avoid.
                #
                # Seen on screen in five rows at once ("Viterna
                # transition width", "Lag constant A", "Fade-out start/end",
                # "Maximum skew angle") -- all from blocks that start
                # switched off. Inheriting the replaced label's visibility
                # is what keeps the row coherent.
                estava_visivel = not label_widget.isHidden()
                label_widget.hide()
                label_widget.setParent(None)  # remove from the scene
                novo_label = _label_clicavel(campo, texto, raiz)
                novo_label.setVisible(estava_visivel)
                form.setWidget(linha, QFormLayout.ItemRole.LabelRole, novo_label)

            widget._tem_popup_de_campo = True
            criados += 1

    # Checkboxes outside a QFormLayout (loose boxes in QVBoxLayout etc.)
    for cb in raiz.findChildren(QCheckBox):
        if getattr(cb, "_tem_popup_de_campo", False):
            continue
        campo = _campo_do_widget(cb)
        if campo is None:
            continue
        if ancora_do_campo(campo) is None and campo not in help_content.FIELD_HELP:
            continue
        if _instalar_no_checkbox(cb, campo, raiz):
            cb._tem_popup_de_campo = True
            criados += 1

    return criados


# Compatibilidade: alguns módulos ainda chamam `anexar_ajuda_de_campo`.
anexar_ajuda_de_campo = instalar_popups_de_campo
